// ECDO Watch Dashboard - Real Geophysics Data Version
// Fetches real scientific data from assets JSON files
// Data generated by generate_ecdo_watch_data.py

const { useState, useEffect, useRef } = React;

// Fallback synthetic data if JSON files not available
const generateKpData = () => {
  const data = [];
  const labels = [];
  const now = new Date();
  for (let i = 13; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    labels.push(date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }));
    data.push(Math.random() * 4 + (Math.random() > 0.85 ? 3 : 0));
  }
  return { labels, data };
};

const generateLODData = () => {
  const data = [];
  const labels = [];
  const now = new Date();
  for (let i = 89; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    labels.push(date.toISOString().split('T')[0]);
    const seasonal = Math.sin((i / 365) * 2 * Math.PI) * 0.8;
    const noise = (Math.random() - 0.5) * 1.5;
    data.push(seasonal + noise);
  }
  return { labels, data };
};

const generateHistoricalAA = (years) => {
  const data = [];
  const labels = [];
  const endYear = 2026;
  const startYear = endYear - years;
  for (let year = startYear; year <= endYear; year++) {
    labels.push(year.toString());
    const centuryTrend = 15 + ((year - 1868) / 150) * 10;
    const solarPhase = ((year - 1868) % 11) / 11 * 2 * Math.PI;
    const solarCycle = Math.sin(solarPhase) * 8;
    const noise = (Math.random() - 0.5) * 6;
    data.push(Math.max(5, centuryTrend + solarCycle + noise));
  }
  return { labels, data };
};

const generateHistoricalPM = (years) => {
  const data = [];
  const labels = [];
  const endYear = 2026;
  const startYear = endYear - years;
  for (let year = startYear; year <= endYear; year++) {
    labels.push(year.toString());
    let amplitude = 170;
    if (year >= 1910 && year <= 1915) amplitude = 200;
    if (year >= 1920 && year <= 1940) amplitude = 100;
    if (year >= 2015) amplitude = 80;
    const beatPhase = ((year - 1846) % 6.3) / 6.3 * 2 * Math.PI;
    const beat = Math.sin(beatPhase) * 30;
    const noise = (Math.random() - 0.5) * 20;
    data.push(Math.max(50, amplitude + beat + noise));
  }
  return { labels, data };
};

const generateMagData = () => {
  const bou = [];
  const frd = [];
  const brw = [];
  const hon = [];
  const composite = [];
  const labels = [];
  const now = new Date();
  for (let i = 59; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    labels.push(date.toISOString().split('T')[0]);
    bou.push((Math.random() - 0.5) * 2);
    frd.push((Math.random() - 0.5) * 2);
    brw.push((Math.random() - 0.5) * 2);
    hon.push((Math.random() - 0.5) * 2);
    composite.push((Math.random() - 0.5) * 1.5);
  }
  return { labels, bou, frd, brw, hon, composite };
};

// Fetch real data from JSON files for a given time range
const fetchDataFromJSON = async (timeRange = '90d') => {
  try {
    const kpRes = await fetch(`./assets/kp_${timeRange}.json`);
    const lodRes = await fetch(`./assets/lod_${timeRange}.json`);
    const aaRes = await fetch('./assets/historical_aa.json');
    const pmRes = await fetch('./assets/historical_pm.json');
    const magRes = await fetch(`./assets/mag_${timeRange}.json`);

    // Fallback to default files if specific range not found
    let kpData, lodData, c20Data, magData;

    if (kpRes.ok) {
      kpData = await kpRes.json();
    } else {
      const fallback = await fetch('./assets/kp_data.json');
      kpData = await fallback.json();
    }

    if (lodRes.ok) {
      lodData = await lodRes.json();
    } else {
      const fallback = await fetch('./assets/lod_data.json');
      lodData = await fallback.json();
    }

    // Fetch C20 data separately
    try {
      const c20Res = await fetch('./assets/c20_data.json');
      c20Data = c20Res.ok ? await c20Res.json() : { labels: [], data: [] };
    } catch {
      c20Data = { labels: [], data: [] };
    }

    if (magRes.ok) {
      magData = await magRes.json();
    } else {
      const fallback = await fetch('./assets/mag_data.json');
      magData = await fallback.json();
    }

    const aaData = await (aaRes.ok ? aaRes.json() : null);
    const pmData = await (pmRes.ok ? pmRes.json() : null);

    // Fetch coherence data
    let coherenceData = null;
    try {
      const cohRes = await fetch('./assets/coherence_data.json');
      coherenceData = cohRes.ok ? await cohRes.json() : null;
    } catch { /* ignore */ }

    return { kpData, lodData, c20Data, aaData: aaData || generateHistoricalAA(50), pmData: pmData || generateHistoricalPM(50), magData, coherenceData };
  } catch (error) {
    console.warn('Could not load real data, using fallback:', error);
    return null;
  }
};

// Chart component wrapper
const ChartComponent = ({ type, data, options, height, quietFlags }) => {
  const canvasRef = useRef(null);
  const chartRef = useRef(null);

  useEffect(() => {
    if (chartRef.current) {
      chartRef.current.destroy();
    }

    const ctx = canvasRef.current.getContext('2d');
    const chartData = { ...data, quietFlags };
    const plugins = options.plugins ? { ...options.plugins } : {};

    // Add quiet day plugin if quiet flags are provided
    const chartOptions = { ...options };
    if (quietFlags && quietFlags.length > 0) {
      chartOptions.plugins = { ...plugins, [quietDayPlugin.id]: true };
    }

    chartRef.current = new Chart(ctx, {
      type: type,
      data: chartData,
      options: chartOptions,
      plugins: quietFlags && quietFlags.length > 0 ? [quietDayPlugin] : []
    });

    return () => {
      if (chartRef.current) {
        chartRef.current.destroy();
      }
    };
  }, [type, data, options, quietFlags]);

  return <canvas ref={canvasRef} style={{ height: height || 150, width: '100%' }} />;
};

const DataFreshnessIndicator = ({ metadata }) => {
  if (!metadata || !metadata.generated_at) {
    return null;
  }

  const generatedAt = new Date(metadata.generated_at);
  const now = new Date();
  const ageMs = now - generatedAt;
  const ageMinutes = Math.floor(ageMs / 60000);
  const ageHours = Math.floor(ageMs / 3600000);
  const ageDays = Math.floor(ageMs / 86400000);

  let ageText = "";
  let ageColor = "#10b981"; // Green

  if (ageMinutes < 60) {
    ageText = `${ageMinutes} minute${ageMinutes !== 1 ? "s" : ""} ago`;
  } else if (ageHours < 24) {
    ageText = `${ageHours} hour${ageHours !== 1 ? "s" : ""} ago`;
    ageColor = ageHours > 12 ? "#f59e0b" : "#10b981"; // Yellow if > 12 hours
  } else {
    ageText = `${ageDays} day${ageDays !== 1 ? "s" : ""} ago`;
    ageColor = "#ef4444"; // Red if > 24 hours
  }

  return (
    <div style={{
      display: 'inline-block',
      background: ageColor + '15',
      border: `1px solid ${ageColor}`,
      borderRadius: 4,
      padding: '4px 8px',
      fontSize: 11,
      color: ageColor,
      fontFamily: 'monospace'
    }}>
      {metadata.source_status === 'ok' ? '✓' : '⚠'} {ageText}
    </div>
  );
};

const DataSourceFooter = ({ kpMetadata, lodMetadata, magMetadata }) => {
  const sources = [];

  if (kpMetadata && kpMetadata.source) {
    sources.push({
      name: kpMetadata.source,
      status: kpMetadata.source_status || 'ok'
    });
  }
  if (lodMetadata && lodMetadata.source) {
    sources.push({
      name: lodMetadata.source,
      status: lodMetadata.source_status || 'ok'
    });
  }
  if (magMetadata && magMetadata.source) {
    sources.push({
      name: magMetadata.source,
      status: magMetadata.source_status || 'ok'
    });
  }

  if (sources.length === 0) return null;

  return (
    <div style={{
      fontSize: 11,
      color: '#7a7a8c',
      marginTop: 20,
      paddingTop: 16,
      borderTop: '1px solid #252532',
      display: 'flex',
      gap: 16,
      flexWrap: 'wrap'
    }}>
      {sources.map((source, idx) => (
        <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <span style={{ color: source.status === 'ok' ? '#10b981' : source.status === 'partial' ? '#f59e0b' : '#ef4444' }}>
            {source.status === 'ok' ? '✓' : source.status === 'partial' ? '⚠' : '✕'}
          </span>
          <span>{source.name}</span>
        </div>
      ))}
    </div>
  );
};

const StatusBanner = ({ level }) => {
  const [showInfo, setShowInfo] = React.useState(false);

  const statusInfo = {
    NOMINAL: {
      color: '#10b981',
      text: 'All parameters within historical bounds',
      description: 'All monitored geophysical signals (Kp, LOD, magnetometer) are within their normal historical ranges. No anomalies detected across monitoring channels.'
    },
    ELEVATED_DIAGNOSTIC: {
      color: '#f59e0b',
      text: 'Single-channel anomaly detected',
      description: 'One monitoring channel has detected a statistical anomaly (±2.5σ or greater). This may represent normal variability or the beginning of a multi-channel event. Continued monitoring recommended.'
    },
    WATCH: {
      color: '#ef4444',
      text: 'Multi-channel coherent anomaly',
      description: 'Multiple independent geophysical channels are showing correlated anomalies. This indicates a potential system-wide geophysical perturbation and warrants close observation.'
    },
  };

  const c = statusInfo[level] || statusInfo.NOMINAL;

  return (
    <>
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: '#0f0f15', border: '1px solid #252532', borderLeft: '4px solid ' + c.color,
        borderRadius: 10, padding: '16px 20px', marginBottom: 16, flexWrap: 'wrap', gap: 16
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{
            width: 12, height: 12, borderRadius: '50%', background: c.color,
            animation: 'pulse 2s infinite'
          }} />
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <h2 style={{ fontFamily: 'monospace', fontSize: 18, margin: 0, color: '#e8e8ed' }}>{level}</h2>
              <button
                onClick={() => setShowInfo(!showInfo)}
                onMouseEnter={() => setShowInfo(true)}
                onMouseLeave={() => setShowInfo(false)}
                style={{
                  background: 'transparent',
                  border: '1px solid #7a7a8c',
                  color: '#7a7a8c',
                  borderRadius: '50%',
                  width: 20,
                  height: 20,
                  fontSize: 12,
                  fontWeight: 'bold',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: 0,
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => {
                  e.target.style.borderColor = c.color;
                  e.target.style.color = c.color;
                  setShowInfo(true);
                }}
                onMouseLeave={(e) => {
                  e.target.style.borderColor = '#7a7a8c';
                  e.target.style.color = '#7a7a8c';
                  setShowInfo(false);
                }}
              >
                i
              </button>
            </div>
            <p style={{ fontSize: 13, color: '#7a7a8c', margin: 0 }}>{c.text}</p>
          </div>
        </div>
        <div style={{ fontSize: 11, color: '#7a7a8c', maxWidth: 280, textAlign: 'right' }}>
          ⚠️ Experimental analysis tool, NOT a prediction system
        </div>
      </div>

      {showInfo && (
        <div style={{
          background: '#16161f', border: '1px solid ' + c.color, borderRadius: 10,
          padding: 16, marginBottom: 16, fontSize: 13, color: '#e8e8ed',
          borderLeft: '4px solid ' + c.color
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }}>
            <div>
              <strong style={{ color: c.color }}>What does this mean?</strong>
              <p style={{ margin: '8px 0 0 0', color: '#a8a8bc' }}>{c.description}</p>

              <strong style={{ color: c.color, display: 'block', marginTop: 12 }}>What we monitor:</strong>
              <ul style={{ margin: '8px 0 0 0', paddingLeft: 20, color: '#a8a8bc' }}>
                <li>External Forcing (Kp index) - Solar wind energy coupling</li>
                <li>Earth Orientation (LOD) - Rotational dynamics</li>
                <li>Ground Magnetometer - Multi-station magnetic field anomalies</li>
                <li>Cross-channel Coherence - Correlated signals across independent systems</li>
              </ul>
            </div>
            <button
              onClick={() => setShowInfo(false)}
              style={{
                background: 'transparent',
                border: 'none',
                color: '#7a7a8c',
                fontSize: 18,
                cursor: 'pointer',
                padding: 0,
                minWidth: 20
              }}
            >
              ×
            </button>
          </div>
        </div>
      )}
    </>
  );
};

const Card = ({ step, title, status, children, info }) => {
  const [showInfo, setShowInfo] = React.useState(false);
  const statusColors = {
    OPEN: '#10b981', NOMINAL: '#10b981', OK: '#10b981',
    CLOSED: '#ef4444', SUPPRESSED: '#ef4444',
    ELEVATED: '#f59e0b',
  };

  return (
    <>
      <div style={{
        background: '#0f0f15', border: '1px solid #252532', borderRadius: 10, overflow: 'hidden'
      }}>
        <div style={{
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          padding: '12px 16px', borderBottom: '1px solid #252532', background: '#16161f'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            {step && <span style={{
              fontFamily: 'monospace', fontSize: 10, color: '#7a7a8c',
              background: '#252532', padding: '2px 6px', borderRadius: 3
            }}>STEP {step}</span>}
            <h3 style={{ fontSize: 14, fontWeight: 600, margin: 0, color: '#e8e8ed' }}>{title}</h3>
            {info && (
              <button
                onClick={() => setShowInfo(!showInfo)}
                onMouseEnter={() => setShowInfo(true)}
                onMouseLeave={() => setShowInfo(false)}
                style={{
                  background: 'transparent',
                  border: '1px solid #7a7a8c',
                  color: '#7a7a8c',
                  borderRadius: '50%',
                  width: 18,
                  height: 18,
                  fontSize: 11,
                  fontWeight: 'bold',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: 0,
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => {
                  e.target.style.borderColor = '#4a9eff';
                  e.target.style.color = '#4a9eff';
                  setShowInfo(true);
                }}
                onMouseLeave={(e) => {
                  e.target.style.borderColor = '#7a7a8c';
                  e.target.style.color = '#7a7a8c';
                  setShowInfo(false);
                }}
              >
                i
              </button>
            )}
          </div>
          <span style={{
            fontFamily: 'monospace', fontSize: 10, fontWeight: 600,
            padding: '4px 8px', borderRadius: 4, textTransform: 'uppercase',
            background: (statusColors[status] || '#6b7280') + '22', color: statusColors[status] || '#6b7280'
          }}>{status}</span>
        </div>
        <div style={{ padding: 16 }}>{children}</div>
      </div>

      {showInfo && info && (
        <div style={{
          background: '#16161f', border: '1px solid #252532', borderRadius: 10,
          padding: 16, marginTop: 12, fontSize: 13, color: '#e8e8ed'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }}>
            <div>
              <strong style={{ color: '#4a9eff', fontSize: 14 }}>Step {step}: {title}</strong>
              <p style={{ margin: '8px 0', color: '#a8a8bc', lineHeight: 1.5 }}>{info.description}</p>

              <strong style={{ color: '#4a9eff', display: 'block', marginTop: 12, fontSize: 12 }}>What we're looking for:</strong>
              <ul style={{ margin: '8px 0 0 0', paddingLeft: 20, color: '#a8a8bc' }}>
                {info.lookingFor.map((item, idx) => (
                  <li key={idx} style={{ marginBottom: 4 }}>{item}</li>
                ))}
              </ul>

              {info.dataSource && (
                <>
                  <strong style={{ color: '#4a9eff', display: 'block', marginTop: 12, fontSize: 12 }}>Data source:</strong>
                  <p style={{ margin: '4px 0 0 0', color: '#a8a8bc' }}>{info.dataSource}</p>
                </>
              )}
            </div>
            <button
              onClick={() => setShowInfo(false)}
              style={{
                background: 'transparent',
                border: 'none',
                color: '#7a7a8c',
                fontSize: 18,
                cursor: 'pointer',
                padding: 0,
                minWidth: 20
              }}
            >
              ×
            </button>
          </div>
        </div>
      )}
    </>
  );
};

const Metric = ({ label, value, status }) => {
  const colors = { positive: '#10b981', negative: '#ef4444', warning: '#f59e0b' };
  return (
    <div style={{ flex: 1, minWidth: 70, background: '#16161f', borderRadius: 6, padding: '10px 12px' }}>
      <div style={{ fontSize: 10, color: '#7a7a8c', textTransform: 'uppercase', marginBottom: 4 }}>{label}</div>
      <div style={{ fontFamily: 'monospace', fontSize: 16, fontWeight: 600, color: colors[status] || '#e8e8ed' }}>{value}</div>
    </div>
  );
};

// Plugin to draw background colors for quiet days
const quietDayPlugin = {
  id: 'quietDayBackground',
  afterDatasetsDraw(chart) {
    const ctx = chart.ctx;
    const xScale = chart.scales.x;
    const yScale = chart.scales.y;

    // Get quiet-day flags from chart data
    const quietFlags = chart.data.quietFlags;
    if (!quietFlags || quietFlags.length === 0) return;

    const chartWidth = xScale.width;
    const chartHeight = yScale.height;
    const startX = xScale.left;
    const startY = yScale.top;
    const barWidth = chartWidth / quietFlags.length;

    quietFlags.forEach((isQuiet, idx) => {
      if (isQuiet) {
        const x = startX + (idx * barWidth);
        ctx.fillStyle = 'rgba(16, 185, 129, 0.05)'; // Green tint for quiet days
        ctx.fillRect(x, startY, barWidth, chartHeight);
      }
    });
  }
};

// Chart.js default options for dark theme
const darkThemeOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: '#16161f',
      borderColor: '#252532',
      borderWidth: 1,
      titleColor: '#e8e8ed',
      bodyColor: '#7a7a8c'
    }
  },
  scales: {
    x: {
      grid: { display: false },
      ticks: { color: '#7a7a8c', font: { size: 9 } }
    },
    y: {
      grid: { color: '#1e1e2a' },
      ticks: { color: '#7a7a8c', font: { size: 9 } }
    }
  }
};

// Helper: Align all recent datasets to common time axis (uses LOD as reference)
const alignRecentData = (kpData, lodData, magData) => {
  if (!lodData || !lodData.labels || lodData.labels.length === 0) {
    return { kpData, lodData, magData };
  }

  const baseLabels = lodData.labels; // 90-day baseline
  const baseLength = baseLabels.length;

  // Align Kp to LOD time axis
  const kpAligned = { labels: baseLabels, data: Array(baseLength).fill(null), is_quiet: Array(baseLength).fill(null) };
  if (kpData && kpData.data) {
    const kpLen = kpData.labels.length;
    const kpStartIdx = baseLength - kpLen;

    if (kpStartIdx >= 0) {
      // Kp data fits within range - place at the end
      kpData.data.forEach((val, i) => {
        kpAligned.data[kpStartIdx + i] = val;
      });
      // Also align quiet-day flags if available
      if (kpData.is_quiet) {
        kpData.is_quiet.forEach((val, i) => {
          kpAligned.is_quiet[kpStartIdx + i] = val;
        });
      }
    } else {
      // Kp data is longer than range - take the most recent baseLength days
      const offset = kpLen - baseLength;
      for (let i = 0; i < baseLength; i++) {
        kpAligned.data[i] = kpData.data[offset + i];
      }
      if (kpData.is_quiet) {
        for (let i = 0; i < baseLength; i++) {
          kpAligned.is_quiet[i] = kpData.is_quiet[offset + i];
        }
      }
    }
  }

  // Align Mag to LOD time axis
  const magAligned = { labels: baseLabels, bou: Array(baseLength).fill(null), frd: Array(baseLength).fill(null), brw: Array(baseLength).fill(null), hon: Array(baseLength).fill(null), composite: Array(baseLength).fill(null) };
  if (magData && magData.labels) {
    const magLen = magData.labels.length;
    const magStartIdx = baseLength - magLen;

    if (magStartIdx >= 0) {
      // Mag data fits within range - place at the end
      const stations = ['bou', 'frd', 'brw', 'hon', 'composite'];
      stations.forEach(station => {
        if (magData[station]) {
          magData[station].forEach((val, i) => {
            magAligned[station][magStartIdx + i] = val;
          });
        }
      });
    } else {
      // Mag data is longer than range - take the most recent baseLength days
      const offset = magLen - baseLength;
      const stations = ['bou', 'frd', 'brw', 'hon', 'composite'];
      stations.forEach(station => {
        if (magData[station]) {
          for (let i = 0; i < baseLength; i++) {
            magAligned[station][i] = magData[station][offset + i];
          }
        }
      });
    }
  }

  return { kpData: kpAligned, lodData, magData: magAligned };
};

function ECDOWatchDashboard() {
  const [selectedTimeRange, setSelectedTimeRange] = useState('90d');
  const [historicalTimeRange, setHistoricalTimeRange] = useState(50);
  const [dataLoaded, setDataLoaded] = useState(false);
  const [kpData, setKpData] = useState(() => generateKpData());
  const [lodData, setLodData] = useState(() => generateLODData());
  const [c20Data, setC20Data] = useState({ labels: [], data: [] });
  const [magData, setMagData] = useState(() => generateMagData());
  const [aaData, setAaData] = useState(() => generateHistoricalAA(historicalTimeRange));
  const [pmData, setPmData] = useState(() => generateHistoricalPM(historicalTimeRange));
  const [coherenceData, setCoherenceData] = useState(null);
  const [compositeMetrics, setCompositeMetrics] = useState({ z: 0, flag: false, maxZ: 0 });
  const [statusLevel, setStatusLevel] = useState('NOMINAL');
  const [alignedData, setAlignedData] = useState(() => alignRecentData(kpData, lodData, magData));
  const [kpMetadata, setKpMetadata] = useState({});
  const [lodMetadata, setLodMetadata] = useState({});
  const [magMetadata, setMagMetadata] = useState({});

  // Load real data from JSON files when time range changes
  useEffect(() => {
    fetchDataFromJSON(selectedTimeRange).then(data => {
      if (data) {
        console.log(`Loaded data for ${selectedTimeRange}:`, { kpLabels: data.kpData.labels.length, lodLabels: data.lodData.labels.length, magLabels: data.magData.labels.length });
        setKpData(data.kpData);
        setLodData(data.lodData);
        setC20Data(data.c20Data);
        setAaData(data.aaData);
        setPmData(data.pmData);
        setMagData(data.magData);
        if (data.coherenceData) setCoherenceData(data.coherenceData);

        // Extract and store metadata
        setKpMetadata(data.kpData.metadata || {});
        setLodMetadata(data.lodData.metadata || {});
        setMagMetadata(data.magData.metadata || {});
      }
      setDataLoaded(true);
    }).catch(err => console.error('Error loading data:', err));
  }, [selectedTimeRange]);

  // Recalculate aligned data whenever individual datasets change
  useEffect(() => {
    const aligned = alignRecentData(kpData, lodData, magData);
    setAlignedData(aligned);
  }, [kpData, lodData, magData]);

  // Update historical data when time range changes
  useEffect(() => {
    setAaData(generateHistoricalAA(historicalTimeRange));
    setPmData(generateHistoricalPM(historicalTimeRange));
  }, [historicalTimeRange]);

  // Calculate composite z-score metrics dynamically
  useEffect(() => {
    if (alignedData.magData && alignedData.magData.composite && alignedData.magData.composite.length > 0) {
      const composite = alignedData.magData.composite;
      const validValues = composite.filter(v => v !== null);
      const recentValues = validValues.slice(-14); // Last 14 days with data
      if (recentValues.length > 0) {
        const maxAbsZ = Math.max(...recentValues.map(v => Math.abs(v)));
        const currentZ = composite[composite.length - 1];
        const flagged = maxAbsZ >= 2.5; // Flag if any recent value >= 2.5 sigma

        setCompositeMetrics({
          z: currentZ !== null ? currentZ.toFixed(2) : "—",
          flag: flagged,
          maxZ: maxAbsZ.toFixed(2)
        });
      }
    }
  }, [alignedData]);

  // Calculate watch status level from coherence data (or fall back to composite metrics)
  useEffect(() => {
    if (coherenceData && coherenceData.badge) {
      const badge = coherenceData.badge;
      if (badge === 'ORANGE') {
        setStatusLevel('WATCH');
      } else if (badge === 'YELLOW' || compositeMetrics.flag) {
        setStatusLevel('ELEVATED_DIAGNOSTIC');
      } else {
        setStatusLevel('NOMINAL');
      }
    } else if (compositeMetrics.flag) {
      setStatusLevel('ELEVATED_DIAGNOSTIC');
    } else {
      setStatusLevel('NOMINAL');
    }
  }, [compositeMetrics, coherenceData]);

  return (
    <div style={{ background: '#08080c', minHeight: '100vh', color: '#e8e8ed', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <style dangerouslySetInnerHTML={{__html: '@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }'}} />
      
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: 20 }}>
        {/* Header */}
        <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20, paddingBottom: 20, borderBottom: '1px solid #252532', flexWrap: 'wrap', gap: 16 }}>
          <div>
            <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>🌍 ECDO Watch</h1>
            <p style={{ color: '#7a7a8c', fontSize: 13, margin: 0 }}>Falsification-first geophysics monitor • Tau Point approach detection</p>
          </div>
          <div>
            <div style={{ marginBottom: 12 }}>
              <div style={{ fontSize: 11, color: '#7a7a8c', marginBottom: 6, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Time Range</div>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                {['30d', '90d', '1y', '5y', '10y'].map(range => (
                  <button
                    key={range}
                    onClick={() => setSelectedTimeRange(range)}
                    style={{
                      background: selectedTimeRange === range ? '#4a9eff' : '#16161f',
                      border: '1px solid #252532',
                      color: selectedTimeRange === range ? '#fff' : '#7a7a8c',
                      padding: '4px 10px',
                      borderRadius: 4,
                      fontSize: 10,
                      fontFamily: 'monospace',
                      cursor: 'pointer',
                      transition: 'all 0.2s ease'
                    }}
                  >
                    {range}
                  </button>
                ))}
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ marginBottom: 8 }}>
                <DataFreshnessIndicator metadata={kpMetadata} />
              </div>
              <div style={{ fontSize: 11 }}>
                <a href="https://theethicalskeptic.com/2024/05/23/master-exothermic-core-mantle-decoupling-dzhanibekov-oscillation-theory/" target="_blank" rel="noopener noreferrer" style={{ color: '#4a9eff', textDecoration: 'none' }}>
                  ECDO Theory
                </a>
              </div>
            </div>
          </div>
        </header>

        <StatusBanner level={statusLevel} />
        
        {/* Main Stack */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          
          {/* Step 1: Gate */}
          <Card step={1} title="External Forcing Gate (Kp Index)" status="OPEN" info={{
            description: "The Kp (planetary K-index) measures solar wind energy input to Earth's magnetosphere. High Kp values indicate strong geomagnetic storms driven by external solar forcing. This step acts as a 'gate' to distinguish internal Earth dynamics from external solar influences.",
            lookingFor: [
              "Kp ≤ 4 on most days (quiet geomagnetic conditions)",
              "Low Dst values (< -50 nT indicates suppressed disturbance)",
              "Absence of sustained high-amplitude fluctuations",
              "When gate is OPEN: Internal anomalies are more meaningful"
            ],
            dataSource: "NOAA SWPC (3-hour Kp) and GFZ (daily historical records since 1932)"
          }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 16, padding: 16, background: '#16161f', borderRadius: 6, marginBottom: 12 }}>
              <span style={{ fontSize: 32 }}>🛡️</span>
              <div>
                <div style={{ color: '#10b981', fontFamily: 'monospace', fontSize: 14, fontWeight: 600 }}>GATE OPEN</div>
                <div style={{ color: '#7a7a8c', fontSize: 11 }}>Internal inference allowed</div>
              </div>
            </div>
            <div style={{ height: 120 }}>
              <ChartComponent
                type="line"
                height={120}
                quietFlags={alignedData.kpData.is_quiet}
                data={{
                  labels: alignedData.kpData.labels,
                  datasets: [{
                    data: alignedData.kpData.data,
                    borderColor: '#4a9eff',
                    backgroundColor: 'rgba(74, 158, 255, 0.1)',
                    fill: true,
                    tension: 0.3,
                    pointRadius: 0
                  }]
                }}
                options={{
                  ...darkThemeOptions,
                  scales: {
                    ...darkThemeOptions.scales,
                    x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 8 } },
                    y: { ...darkThemeOptions.scales.y }
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 12, flexWrap: 'wrap' }}>
              <Metric label="Kp Max" value="2.3" status="positive" />
              <Metric label="Dst" value="-12 nT" status="positive" />
              <Metric
                label="Quiet Days"
                value={kpData && kpData.is_quiet ? `${kpData.is_quiet.filter(x => x).length}/${kpData.is_quiet.length}` : "—"}
                status="positive"
              />
            </div>
          </Card>
          
          {/* Step 2: EOP */}
          <Card step={2} title="Earth Orientation (LOD + Polar Motion)" status="NOMINAL" info={{
            description: "Earth Orientation Parameters track variations in Earth's rotation rate (LOD) and polar motion speed. Changes reflect mass redistribution and angular momentum exchange within Earth's core, mantle, and atmosphere. The EOP composite combines both channels: max(|z_LOD|, |z_PM_speed|).",
            lookingFor: [
              "LOD anomalies within ±2 milliseconds (normal range)",
              "Low z-score values (< 2σ from 10-year baseline)",
              "Smooth seasonal variation pattern",
              "Coherent spikes in both LOD and polar motion suggest internal perturbations"
            ],
            dataSource: "IERS (International Earth Rotation Service) finals2000A all-time CSV"
          }}>
            <div style={{ height: 160 }}>
              <ChartComponent
                type="line"
                height={160}
                data={{
                  labels: lodData.labels || [],
                  datasets: [
                    {
                      label: 'z(LOD)',
                      data: lodData.z_lod || [],
                      borderColor: '#4a9eff',
                      borderWidth: 1.5,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      label: 'z(PM speed)',
                      data: lodData.z_pm_speed || [],
                      borderColor: '#f59e0b',
                      borderWidth: 1.5,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      label: 'EOP composite',
                      data: lodData.eop_composite || [],
                      borderColor: '#ffffff',
                      borderWidth: 2,
                      tension: 0.3,
                      pointRadius: 0,
                    }
                  ]
                }}
                options={{
                  ...darkThemeOptions,
                  plugins: {
                    ...darkThemeOptions.plugins,
                    legend: {
                      display: true,
                      position: 'top',
                      labels: { color: '#7a7a8c', boxWidth: 12, padding: 8, font: { size: 10 } }
                    }
                  },
                  scales: {
                    x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 8 } },
                    y: { ...darkThemeOptions.scales.y, title: { display: true, text: 'z-score', color: '#7a7a8c', font: { size: 10 } } }
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
              <Metric
                label="LOD z"
                value={(() => { const arr = lodData.z_lod || []; const v = arr[arr.length - 1]; return v != null ? v.toFixed(2) : "—"; })()}
                status={(() => { const arr = lodData.z_lod || []; const v = arr[arr.length - 1]; return v != null && Math.abs(v) >= 2.5 ? "warning" : "positive"; })()}
              />
              <Metric
                label="PM Speed z"
                value={(() => { const arr = lodData.z_pm_speed || []; const v = arr[arr.length - 1]; return v != null ? v.toFixed(2) : "—"; })()}
                status={(() => { const arr = lodData.z_pm_speed || []; const v = arr[arr.length - 1]; return v != null && Math.abs(v) >= 2.5 ? "warning" : "positive"; })()}
              />
              <Metric
                label="EOP Composite"
                value={(() => { const arr = lodData.eop_composite || []; const v = arr[arr.length - 1]; return v != null ? v.toFixed(2) : "—"; })()}
                status={(() => { const arr = lodData.eop_composite || []; const v = arr[arr.length - 1]; return v != null && Math.abs(v) >= 2.5 ? "warning" : "positive"; })()}
              />
            </div>
          </Card>
          
          {/* Step 3: C20 */}
          <Card step={3} title="Mass Distribution (C20)" status="OK" info={{
            description: "C20 (degree-2, order-0 spherical harmonic coefficient) represents Earth's oblateness and mass distribution. Changes in C20 reflect deep mass movements in the core-mantle system and glacial isostatic adjustment (GIA). This is a slow-changing but highly significant indicator of internal Earth structure.",
            lookingFor: [
              "C20 trending within GIA predictions (accounting for post-glacial rebound)",
              "Z-score anomalies isolated to this channel (not corroborated by faster channels)",
              "This is a confirmatory (lagged) channel, not a leading indicator",
              "Large deviations from GIA model suggest unusual deep mantle activity"
            ],
            dataSource: "NASA GSFC SLR (Satellite Laser Ranging) long-term C20 record"
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', background: '#16161f', borderRadius: 6, marginBottom: 12, fontSize: 11, color: '#7a7a8c' }}>
              📡 C20 data: <strong style={{ color: '#e8e8ed' }}>{c20Data && c20Data.labels ? `${c20Data.labels.length} days` : 'Loading...'}</strong>
            </div>
            <div style={{ height: 100 }}>
              <ChartComponent
                type="line"
                height={100}
                data={{
                  labels: c20Data && c20Data.labels ? c20Data.labels : [],
                  datasets: [{
                    data: c20Data && c20Data.data ? c20Data.data : [],
                    borderColor: '#10b981',
                    tension: 0.3,
                    pointRadius: 0
                  }]
                }}
                options={{
                  ...darkThemeOptions,
                  scales: {
                    x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 8 } },
                    y: { ...darkThemeOptions.scales.y }
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
              <Metric label="C20 z (recent)" value={c20Data && c20Data.data && c20Data.data.length > 0 && c20Data.data[c20Data.data.length - 1] !== null ? c20Data.data[c20Data.data.length - 1].toFixed(2) : "—"} status="positive" />
              <Metric label="vs GIA" value="Normal" status="positive" />
            </div>
            <div style={{ marginTop: 12, paddingTop: 12, borderTop: '1px solid #252532', fontSize: 11, color: '#7a7a8c', textAlign: 'center' }}>
              ⏱️ Lagged confirmatory channel
            </div>
          </Card>
          
          {/* Step 4: Magnetometer */}
          <Card step={4} title="Ground Magnetic (Multi-Station)" status="NOMINAL" info={{
            description: "Ground-based magnetometer observations measure horizontal magnetic field perturbations at four USGS stations (Boulder, Fredericksburg, Barrow, Honolulu). Multi-station coherence filters out local/instrumental noise and identifies true geomagnetic signals. High z-scores across multiple stations indicate significant internal magnetic anomalies.",
            lookingFor: [
              "Composite z-score within ±2σ (normal baseline range)",
              "Coherent signals across 3+ stations (not isolated single-site noise)",
              "Spikes ≥ 2.5σ warrant attention if sustained or multi-channel correlated",
              "Recent observation: 7.7σ spike on 2026-01-25 (observed across multiple stations)"
            ],
            dataSource: "USGS Geomagnetic Monitoring Program (4 monitoring stations, 60-day window)"
          }}>
            <div style={{ height: 180 }}>
              <ChartComponent
                type="line"
                height={180}
                data={{
                  labels: alignedData.magData.labels,
                  datasets: [
                    {
                      label: 'Boulder',
                      data: alignedData.magData.bou,
                      borderColor: '#4a9eff',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      label: 'Fredericksburg',
                      data: alignedData.magData.frd,
                      borderColor: '#f59e0b',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0
                    },
                    {
                      label: 'Barrow',
                      data: alignedData.magData.brw,
                      borderColor: '#10b981',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0
                    },
                    {
                      label: 'Honolulu',
                      data: alignedData.magData.hon,
                      borderColor: '#8b5cf6',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0
                    },
                    {
                      label: 'Composite',
                      data: alignedData.magData.composite,
                      borderColor: '#ffffff',
                      borderWidth: 2,
                      tension: 0.3,
                      pointRadius: 0
                    }
                  ]
                }}
                options={{
                  ...darkThemeOptions,
                  plugins: {
                    ...darkThemeOptions.plugins,
                    legend: {
                      display: true,
                      position: 'top',
                      labels: {
                        color: '#7a7a8c',
                        boxWidth: 12,
                        padding: 8,
                        font: { size: 10 }
                      }
                    }
                  },
                  scales: {
                    x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 8 } },
                    y: { ...darkThemeOptions.scales.y }
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
              <Metric label="Composite z" value={compositeMetrics.z} status={Math.abs(parseFloat(compositeMetrics.z)) >= 2.5 ? "negative" : "positive"} />
              <Metric label="Max z (14d)" value={compositeMetrics.maxZ} status={compositeMetrics.flag ? "warning" : "positive"} />
              <Metric label="Flag" value={compositeMetrics.flag ? "⚠ YES" : "✓ No"} status={compositeMetrics.flag ? "warning" : "positive"} />
            </div>
          </Card>
          
          {/* Step 5: Coherence */}
          <Card step={5} title="Cross-Channel Coherence" status={coherenceData && coherenceData.badge === 'ORANGE' ? 'ELEVATED' : 'NOMINAL'} info={{
            description: "Cross-channel coherence analyzes whether anomalies detected in independent monitoring systems (EOP and magnetometer) are correlated in time. True geophysical events show up across multiple independent channels. The watch score combines EOP and MAG composites on quiet days only: 100 × (0.6 × EOP_signal + 0.4 × MAG_signal).",
            lookingFor: [
              "Low correlation (< 0.3) is normal: independent systems track different phenomena",
              "Elevated correlation during quiet days suggests genuine coherent signal",
              "EOP↔MAG correlation ≥ 0.5 during gate-open conditions = WATCH-level event",
              "Watch score: GREEN (<35), YELLOW (35-65), ORANGE (≥65), GRAY (disturbed gate)"
            ],
            dataSource: "Derived from Steps 2 and 4 using quiet-day-gated correlation analysis (30-day rolling window, N≥10 required)"
          }}>
            {coherenceData && coherenceData.labels && coherenceData.labels.length > 0 ? (
              <>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8, marginBottom: 12 }}>
                  <div style={{ background: '#16161f', borderRadius: 6, padding: 12, textAlign: 'center' }}>
                    <div style={{ fontSize: 10, color: '#7a7a8c', marginBottom: 4 }}>QUIET DAYS (90d)</div>
                    <div style={{ fontFamily: 'monospace', fontSize: 20, fontWeight: 600, color: '#4a9eff' }}>
                      {coherenceData.quiet_day_count}/{coherenceData.total_days}
                    </div>
                  </div>
                  <div style={{ background: '#16161f', borderRadius: 6, padding: 12, textAlign: 'center' }}>
                    <div style={{ fontSize: 10, color: '#7a7a8c', marginBottom: 4 }}>WATCH SCORE</div>
                    <div style={{ fontFamily: 'monospace', fontSize: 20, fontWeight: 600, color:
                      coherenceData.badge === 'GREEN' ? '#10b981' :
                      coherenceData.badge === 'YELLOW' ? '#f59e0b' :
                      coherenceData.badge === 'ORANGE' ? '#ef4444' : '#7a7a8c'
                    }}>
                      {coherenceData.latest_watch_score != null ? coherenceData.latest_watch_score.toFixed(0) : "—"}
                    </div>
                  </div>
                  <div style={{ background: '#16161f', borderRadius: 6, padding: 12, textAlign: 'center' }}>
                    <div style={{ fontSize: 10, color: '#7a7a8c', marginBottom: 4 }}>BADGE</div>
                    <div style={{ fontFamily: 'monospace', fontSize: 20, fontWeight: 600, color:
                      coherenceData.badge === 'GREEN' ? '#10b981' :
                      coherenceData.badge === 'YELLOW' ? '#f59e0b' :
                      coherenceData.badge === 'ORANGE' ? '#ef4444' : '#7a7a8c'
                    }}>
                      {coherenceData.badge}
                    </div>
                  </div>
                </div>

                {/* Composite overlay chart: EOP vs MAG */}
                <div style={{ height: 160, marginBottom: 12 }}>
                  <ChartComponent
                    type="line"
                    height={160}
                    data={{
                      labels: coherenceData.labels,
                      datasets: [
                        {
                          label: 'EOP composite',
                          data: coherenceData.eop_composite,
                          borderColor: '#4a9eff',
                          borderWidth: 1.5,
                          tension: 0.3,
                          pointRadius: 0,
                        },
                        {
                          label: 'MAG composite',
                          data: coherenceData.mag_composite,
                          borderColor: '#f59e0b',
                          borderWidth: 1.5,
                          tension: 0.3,
                          pointRadius: 0,
                        }
                      ]
                    }}
                    options={{
                      ...darkThemeOptions,
                      plugins: {
                        ...darkThemeOptions.plugins,
                        legend: {
                          display: true,
                          position: 'top',
                          labels: { color: '#7a7a8c', boxWidth: 12, padding: 8, font: { size: 10 } }
                        }
                      },
                      scales: {
                        x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 8 } },
                        y: { ...darkThemeOptions.scales.y, title: { display: true, text: 'composite score', color: '#7a7a8c', font: { size: 10 } } }
                      }
                    }}
                  />
                </div>

                {/* Watch score chart */}
                <div style={{ height: 100, marginBottom: 12 }}>
                  <ChartComponent
                    type="line"
                    height={100}
                    data={{
                      labels: coherenceData.labels,
                      quietFlags: coherenceData.quiet,
                      datasets: [{
                        label: 'Watch score',
                        data: coherenceData.watch_score,
                        borderColor: '#10b981',
                        backgroundColor: 'rgba(16, 185, 129, 0.1)',
                        fill: true,
                        tension: 0.3,
                        pointRadius: 0,
                      }]
                    }}
                    options={{
                      ...darkThemeOptions,
                      plugins: { ...darkThemeOptions.plugins, legend: { display: false } },
                      scales: {
                        x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 8 } },
                        y: { ...darkThemeOptions.scales.y, min: 0, max: 100, title: { display: true, text: 'score (0-100)', color: '#7a7a8c', font: { size: 10 } } }
                      }
                    }}
                    quietFlags={coherenceData.quiet}
                  />
                </div>

                <div style={{ display: 'flex', gap: 8 }}>
                  <Metric
                    label="EOP↔MAG r"
                    value={coherenceData.correlation != null ? coherenceData.correlation.toFixed(2) : "n/a"}
                    status={coherenceData.correlation != null && Math.abs(coherenceData.correlation) >= 0.5 ? "warning" : "positive"}
                  />
                  <Metric
                    label="N (quiet)"
                    value={`${coherenceData.quiet_day_count}`}
                    status={coherenceData.quiet_day_count >= 10 ? "positive" : "warning"}
                  />
                </div>
              </>
            ) : (
              <div style={{ padding: 20, textAlign: 'center', color: '#7a7a8c', fontSize: 13 }}>
                Coherence data not yet available. Run the data pipeline to generate.
              </div>
            )}
          </Card>
          
          {/* Historical Section */}
          <Card title="📊 Century-Scale Historical Context">
            <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' }}>
              {[10, 50, 100, 150].map(function(y) {
                return (
                  <button key={y} onClick={function() { setHistoricalTimeRange(y); }} style={{
                    background: historicalTimeRange === y ? '#4a9eff' : '#16161f',
                    border: '1px solid #252532', color: historicalTimeRange === y ? '#fff' : '#7a7a8c',
                    padding: '4px 12px', borderRadius: 4, fontSize: 11, fontFamily: 'monospace', cursor: 'pointer'
                  }}>{y}Y</button>
                );
              })}
            </div>
            
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 16 }}>
              <div>
                <h4 style={{ fontSize: 12, color: '#7a7a8c', marginBottom: 8 }}>Geomagnetic Ap Index (since 1932)</h4>
                <div style={{ height: 200 }}>
                  <ChartComponent
                    type="line"
                    height={200}
                    data={{
                      labels: aaData.labels,
                      datasets: [{
                        data: aaData.data,
                        borderColor: '#f59e0b',
                        backgroundColor: 'rgba(245, 158, 11, 0.1)',
                        fill: true,
                        tension: 0.3,
                        pointRadius: 0
                      }]
                    }}
                    options={{
                      ...darkThemeOptions,
                      scales: {
                        ...darkThemeOptions.scales,
                        x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 10 } },
                        y: { ...darkThemeOptions.scales.y }
                      }
                    }}
                  />
                </div>
              </div>
              
              <div>
                <h4 style={{ fontSize: 12, color: '#7a7a8c', marginBottom: 8 }}>Polar Motion Amplitude (since 1846)</h4>
                <div style={{ height: 200 }}>
                  <ChartComponent
                    type="line"
                    height={200}
                    data={{
                      labels: pmData.labels,
                      datasets: [{
                        data: pmData.data,
                        borderColor: '#10b981',
                        backgroundColor: 'rgba(16, 185, 129, 0.1)',
                        fill: true,
                        tension: 0.3,
                        pointRadius: 0
                      }]
                    }}
                    options={{
                      ...darkThemeOptions,
                      scales: {
                        ...darkThemeOptions.scales,
                        x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 10 } },
                        y: { ...darkThemeOptions.scales.y }
                      }
                    }}
                  />
                </div>
              </div>
            </div>
            
            <div style={{ display: 'flex', gap: 16, marginTop: 16, flexWrap: 'wrap' }}>
              <Metric label="Ap Record" value="1932–Now" />
              <Metric label="PM Record" value="1846–Now" />
              <Metric label="LOD Record" value="1623–Now" />
              <Metric label="Current Regime" value="Within Bounds" status="positive" />
            </div>
            
            <div style={{ marginTop: 16, padding: 12, background: '#16161f', borderRadius: 6, fontSize: 11, color: '#7a7a8c' }}>
              📚 <strong>Data sources:</strong> Ap index from GFZ (1932–present); Polar motion from IERS C01 (1846–present); LOD from IERS (yearly since 1623).
            </div>
          </Card>
          
        </div>

        <DataSourceFooter kpMetadata={kpMetadata} lodMetadata={lodMetadata} magMetadata={magMetadata} />

        {/* Footer */}
        <footer style={{ marginTop: 24, paddingTop: 16, borderTop: '1px solid #252532', fontSize: 11, color: '#7a7a8c', textAlign: 'left' }}>
          ⚠️ This is an experimental analysis tool, NOT a prediction system. Watch levels indicate statistical anomalies relative to historical baselines, not probabilities of future events.
        </footer>
      </div>
    </div>
  );
}
