// ECDO Watch Dashboard - Real Geophysics Data Version
// Fetches real scientific data from assets JSON files
// Data generated by generate_ecdo_watch_data.py

const { useState, useEffect, useRef } = React;

const useWindowWidth = () => {
  const [width, setWidth] = useState(window.innerWidth);
  useEffect(() => {
    const handleResize = () => setWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);
  return width;
};

// Fallback synthetic data if JSON files not available
const generateKpData = () => {
  const data = [];
  const labels = [];
  const now = new Date();
  for (let i = 13; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    labels.push(date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }));
    data.push(Math.random() * 4 + (Math.random() > 0.85 ? 3 : 0));
  }
  return { labels, data };
};

const generateLODData = () => {
  const data = [];
  const labels = [];
  const now = new Date();
  for (let i = 89; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    labels.push(date.toISOString().split('T')[0]);
    const seasonal = Math.sin((i / 365) * 2 * Math.PI) * 0.8;
    const noise = (Math.random() - 0.5) * 1.5;
    data.push(seasonal + noise);
  }
  return { labels, data };
};

const generateHistoricalAA = (years) => {
  const data = [];
  const labels = [];
  const endYear = 2026;
  const startYear = endYear - years;
  for (let year = startYear; year <= endYear; year++) {
    labels.push(year.toString());
    const centuryTrend = 15 + ((year - 1868) / 150) * 10;
    const solarPhase = ((year - 1868) % 11) / 11 * 2 * Math.PI;
    const solarCycle = Math.sin(solarPhase) * 8;
    const noise = (Math.random() - 0.5) * 6;
    data.push(Math.max(5, centuryTrend + solarCycle + noise));
  }
  return { labels, data };
};

const generateHistoricalPM = (years) => {
  const data = [];
  const labels = [];
  const endYear = 2026;
  const startYear = endYear - years;
  for (let year = startYear; year <= endYear; year++) {
    labels.push(year.toString());
    let amplitude = 170;
    if (year >= 1910 && year <= 1915) amplitude = 200;
    if (year >= 1920 && year <= 1940) amplitude = 100;
    if (year >= 2015) amplitude = 80;
    const beatPhase = ((year - 1846) % 6.3) / 6.3 * 2 * Math.PI;
    const beat = Math.sin(beatPhase) * 30;
    const noise = (Math.random() - 0.5) * 20;
    data.push(Math.max(50, amplitude + beat + noise));
  }
  return { labels, data };
};

const generateMagData = () => {
  const bou = [];
  const frd = [];
  const brw = [];
  const hon = [];
  const composite = [];
  const labels = [];
  const now = new Date();
  for (let i = 59; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    labels.push(date.toISOString().split('T')[0]);
    bou.push((Math.random() - 0.5) * 2);
    frd.push((Math.random() - 0.5) * 2);
    brw.push((Math.random() - 0.5) * 2);
    hon.push((Math.random() - 0.5) * 2);
    composite.push((Math.random() - 0.5) * 1.5);
  }
  return { labels, bou, frd, brw, hon, composite };
};

// Fetch real data from JSON files for a given time range
const fetchDataFromJSON = async (timeRange = '90d') => {
  try {
    const kpRes = await fetch(`./assets/kp_${timeRange}.json`);
    const lodRes = await fetch(`./assets/lod_${timeRange}.json`);
    const aaRes = await fetch('./assets/historical_aa.json');
    const pmRes = await fetch('./assets/historical_pm.json');
    const magRes = await fetch(`./assets/mag_${timeRange}.json`);

    // Fallback to default files if specific range not found
    let kpData, lodData, c20Data, magData;

    if (kpRes.ok) {
      kpData = await kpRes.json();
    } else {
      const fallback = await fetch('./assets/kp_data.json');
      kpData = await fallback.json();
    }

    if (lodRes.ok) {
      lodData = await lodRes.json();
    } else {
      const fallback = await fetch('./assets/lod_data.json');
      lodData = await fallback.json();
    }

    // Fetch C20 data separately
    try {
      const c20Res = await fetch('./assets/c20_data.json');
      c20Data = c20Res.ok ? await c20Res.json() : { labels: [], data: [] };
    } catch {
      c20Data = { labels: [], data: [] };
    }

    if (magRes.ok) {
      magData = await magRes.json();
    } else {
      const fallback = await fetch('./assets/mag_data.json');
      magData = await fallback.json();
    }

    const aaData = await (aaRes.ok ? aaRes.json() : null);
    const pmData = await (pmRes.ok ? pmRes.json() : null);

    // Fetch coherence data
    let coherenceData = null;
    try {
      const cohRes = await fetch('./assets/coherence_data.json');
      coherenceData = cohRes.ok ? await cohRes.json() : null;
    } catch { /* ignore */ }

    // Fetch deep seismicity data
    let seisData = null;
    try {
      const seisRes = await fetch(`./assets/seis_${timeRange}.json`);
      if (seisRes.ok) {
        seisData = await seisRes.json();
      } else {
        const seisFallback = await fetch('./assets/deep_seismicity_data.json');
        seisData = seisFallback.ok ? await seisFallback.json() : null;
      }
    } catch { /* ignore */ }

    // Fetch volcanic activity data
    let volcData = null;
    try {
      const volcRes = await fetch('./assets/volcanic_activity_data.json');
      volcData = volcRes.ok ? await volcRes.json() : null;
    } catch { /* ignore */ }

    // Fetch polar motion data
    let polarMotionData = null;
    try {
      const pmrRes = await fetch('./assets/polar_motion_data.json');
      polarMotionData = pmrRes.ok ? await pmrRes.json() : null;
    } catch { /* ignore */ }

    // Fetch seismic events for globe
    let seismicEventsData = null;
    try {
      const seRes = await fetch('./assets/seismic_events.json');
      seismicEventsData = seRes.ok ? await seRes.json() : null;
    } catch { /* ignore */ }

    return { kpData, lodData, c20Data, aaData: aaData || generateHistoricalAA(50), pmData: pmData || generateHistoricalPM(50), magData, coherenceData, seisData, volcData, polarMotionData, seismicEventsData };
  } catch (error) {
    console.warn('Could not load real data, using fallback:', error);
    return null;
  }
};

// Chart component wrapper
const ChartComponent = ({ type, data, options, height, quietFlags }) => {
  const canvasRef = useRef(null);
  const chartRef = useRef(null);

  useEffect(() => {
    if (chartRef.current) {
      chartRef.current.destroy();
    }

    const ctx = canvasRef.current.getContext('2d');
    const chartData = { ...data, quietFlags };
    const plugins = options.plugins ? { ...options.plugins } : {};

    // Add quiet day plugin if quiet flags are provided
    const chartOptions = { ...options };
    if (quietFlags && quietFlags.length > 0) {
      chartOptions.plugins = { ...plugins, [quietDayPlugin.id]: true };
    }

    chartRef.current = new Chart(ctx, {
      type: type,
      data: chartData,
      options: chartOptions,
      plugins: quietFlags && quietFlags.length > 0 ? [quietDayPlugin] : []
    });

    return () => {
      if (chartRef.current) {
        chartRef.current.destroy();
      }
    };
  }, [type, data, options, quietFlags]);

  return <canvas ref={canvasRef} style={{ height: height || 150, width: '100%' }} />;
};

const DataFreshnessIndicator = ({ metadata }) => {
  if (!metadata || !metadata.generated_at) {
    return null;
  }

  const generatedAt = new Date(metadata.generated_at);
  const now = new Date();
  const ageMs = now - generatedAt;
  const ageMinutes = Math.floor(ageMs / 60000);
  const ageHours = Math.floor(ageMs / 3600000);
  const ageDays = Math.floor(ageMs / 86400000);

  let ageText = "";
  let ageColor = "#10b981"; // Green

  if (ageMinutes < 60) {
    ageText = `${ageMinutes} minute${ageMinutes !== 1 ? "s" : ""} ago`;
  } else if (ageHours < 24) {
    ageText = `${ageHours} hour${ageHours !== 1 ? "s" : ""} ago`;
    ageColor = ageHours > 12 ? "#f59e0b" : "#10b981"; // Yellow if > 12 hours
  } else {
    ageText = `${ageDays} day${ageDays !== 1 ? "s" : ""} ago`;
    ageColor = "#ef4444"; // Red if > 24 hours
  }

  return (
    <div style={{
      display: 'inline-block',
      background: ageColor + '15',
      border: `1px solid ${ageColor}`,
      borderRadius: 4,
      padding: '4px 8px',
      fontSize: 11,
      color: ageColor,
      fontFamily: 'monospace'
    }}>
      {metadata.source_status === 'ok' ? '✓' : '⚠'} {ageText}
    </div>
  );
};

const DataSourceFooter = ({ kpMetadata, lodMetadata, magMetadata }) => {
  const sources = [];

  if (kpMetadata && kpMetadata.source) {
    sources.push({
      name: kpMetadata.source,
      status: kpMetadata.source_status || 'ok'
    });
  }
  if (lodMetadata && lodMetadata.source) {
    sources.push({
      name: lodMetadata.source,
      status: lodMetadata.source_status || 'ok'
    });
  }
  if (magMetadata && magMetadata.source) {
    sources.push({
      name: magMetadata.source,
      status: magMetadata.source_status || 'ok'
    });
  }

  if (sources.length === 0) return null;

  return (
    <div style={{
      fontSize: 11,
      color: '#7a7a8c',
      marginTop: 20,
      paddingTop: 16,
      borderTop: '1px solid #252532',
      display: 'flex',
      gap: 16,
      flexWrap: 'wrap'
    }}>
      {sources.map((source, idx) => (
        <div key={idx} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          <span style={{ color: source.status === 'ok' ? '#10b981' : source.status === 'partial' ? '#f59e0b' : '#ef4444' }}>
            {source.status === 'ok' ? '✓' : source.status === 'partial' ? '⚠' : '✕'}
          </span>
          <span>{source.name}</span>
        </div>
      ))}
    </div>
  );
};

const Card = ({ step, title, status, children, info }) => {
  const [showInfo, setShowInfo] = React.useState(false);
  const statusColors = {
    OPEN: '#10b981', NOMINAL: '#10b981', OK: '#10b981',
    CLOSED: '#ef4444', SUPPRESSED: '#ef4444',
    ELEVATED: '#f59e0b',
  };

  return (
    <>
      <div style={{
        background: '#0f0f15', border: '1px solid #252532', borderRadius: 10, overflow: 'hidden'
      }}>
        <div style={{
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          padding: '12px 16px', borderBottom: '1px solid #252532', background: '#16161f'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            {step && <span style={{
              fontFamily: 'monospace', fontSize: 10, color: '#7a7a8c',
              background: '#252532', padding: '2px 6px', borderRadius: 3
            }}>STEP {step}</span>}
            <h3 style={{ fontSize: 14, fontWeight: 600, margin: 0, color: '#e8e8ed' }}>{title}</h3>
            {info && (
              <button
                onClick={() => setShowInfo(!showInfo)}
                onMouseEnter={() => setShowInfo(true)}
                onMouseLeave={() => setShowInfo(false)}
                style={{
                  background: 'transparent',
                  border: '1px solid #7a7a8c',
                  color: '#7a7a8c',
                  borderRadius: '50%',
                  width: 18,
                  height: 18,
                  fontSize: 11,
                  fontWeight: 'bold',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: 0,
                  transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => {
                  e.target.style.borderColor = '#4a9eff';
                  e.target.style.color = '#4a9eff';
                  setShowInfo(true);
                }}
                onMouseLeave={(e) => {
                  e.target.style.borderColor = '#7a7a8c';
                  e.target.style.color = '#7a7a8c';
                  setShowInfo(false);
                }}
              >
                i
              </button>
            )}
          </div>
          <span style={{
            fontFamily: 'monospace', fontSize: 10, fontWeight: 600,
            padding: '4px 8px', borderRadius: 4, textTransform: 'uppercase',
            background: (statusColors[status] || '#6b7280') + '22', color: statusColors[status] || '#6b7280'
          }}>{status}</span>
        </div>
        <div style={{ padding: 16 }}>{children}</div>
      </div>

      {showInfo && info && (
        <div style={{
          background: '#16161f', border: '1px solid #252532', borderRadius: 10,
          padding: 16, marginTop: 12, fontSize: 13, color: '#e8e8ed'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }}>
            <div>
              <strong style={{ color: '#4a9eff', fontSize: 14 }}>Step {step}: {title}</strong>
              <p style={{ margin: '8px 0', color: '#a8a8bc', lineHeight: 1.5 }}>{info.description}</p>

              <strong style={{ color: '#4a9eff', display: 'block', marginTop: 12, fontSize: 12 }}>What we're looking for:</strong>
              <ul style={{ margin: '8px 0 0 0', paddingLeft: 20, color: '#a8a8bc' }}>
                {info.lookingFor.map((item, idx) => (
                  <li key={idx} style={{ marginBottom: 4 }}>{item}</li>
                ))}
              </ul>

              {info.dataSource && (
                <>
                  <strong style={{ color: '#4a9eff', display: 'block', marginTop: 12, fontSize: 12 }}>Data source:</strong>
                  <p style={{ margin: '4px 0 0 0', color: '#a8a8bc' }}>{info.dataSource}</p>
                </>
              )}
            </div>
            <button
              onClick={() => setShowInfo(false)}
              style={{
                background: 'transparent',
                border: 'none',
                color: '#7a7a8c',
                fontSize: 18,
                cursor: 'pointer',
                padding: 0,
                minWidth: 20
              }}
            >
              ×
            </button>
          </div>
        </div>
      )}
    </>
  );
};

const Metric = ({ label, value, status }) => {
  const colors = { positive: '#10b981', negative: '#ef4444', warning: '#f59e0b' };
  return (
    <div style={{ flex: 1, minWidth: 70, background: '#16161f', borderRadius: 6, padding: '10px 12px' }}>
      <div style={{ fontSize: 10, color: '#7a7a8c', textTransform: 'uppercase', marginBottom: 4 }}>{label}</div>
      <div style={{ fontFamily: 'monospace', fontSize: 16, fontWeight: 600, color: colors[status] || '#e8e8ed' }}>{value}</div>
    </div>
  );
};

const CompactCard = ({ step, title, status, subtitle, children }) => {
  const statusColors = {
    OPEN: '#10b981', NOMINAL: '#10b981', OK: '#10b981',
    CLOSED: '#ef4444', SUPPRESSED: '#ef4444',
    ELEVATED: '#f59e0b',
  };

  return (
    <div style={{
      background: '#0f0f15', border: '1px solid #252532', borderRadius: 8, overflow: 'hidden'
    }}>
      <div style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '6px 10px', borderBottom: '1px solid #252532', background: '#16161f',
        minHeight: 32,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, minWidth: 0 }}>
          {step && <span style={{
            fontFamily: 'monospace', fontSize: 9, color: '#7a7a8c',
            background: '#252532', padding: '1px 5px', borderRadius: 3, flexShrink: 0,
          }}>S{step}</span>}
          <h3 style={{ fontSize: 12, fontWeight: 600, margin: 0, color: '#e8e8ed', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{title}</h3>
          {subtitle && <span style={{ fontSize: 9, color: '#7a7a8c', whiteSpace: 'nowrap', flexShrink: 0 }}>{subtitle}</span>}
        </div>
        <span style={{
          fontFamily: 'monospace', fontSize: 9, fontWeight: 600,
          padding: '2px 6px', borderRadius: 3, textTransform: 'uppercase', flexShrink: 0,
          background: (statusColors[status] || '#6b7280') + '22', color: statusColors[status] || '#6b7280'
        }}>{status}</span>
      </div>
      <div style={{ padding: 10 }}>{children}</div>
    </div>
  );
};

const CompactMetric = ({ label, value, status }) => {
  const colors = { positive: '#10b981', negative: '#ef4444', warning: '#f59e0b' };
  return (
    <div style={{ flex: 1, minWidth: 55, background: '#16161f', borderRadius: 4, padding: '5px 7px' }}>
      <div style={{ fontSize: 8, color: '#7a7a8c', textTransform: 'uppercase', marginBottom: 2 }}>{label}</div>
      <div style={{ fontFamily: 'monospace', fontSize: 13, fontWeight: 600, color: colors[status] || '#e8e8ed' }}>{value}</div>
    </div>
  );
};

// Plugin to draw background colors for quiet days
const quietDayPlugin = {
  id: 'quietDayBackground',
  afterDatasetsDraw(chart) {
    const ctx = chart.ctx;
    const xScale = chart.scales.x;
    const yScale = chart.scales.y;

    // Get quiet-day flags from chart data
    const quietFlags = chart.data.quietFlags;
    if (!quietFlags || quietFlags.length === 0) return;

    const chartWidth = xScale.width;
    const chartHeight = yScale.height;
    const startX = xScale.left;
    const startY = yScale.top;
    const barWidth = chartWidth / quietFlags.length;

    quietFlags.forEach((isQuiet, idx) => {
      if (isQuiet) {
        const x = startX + (idx * barWidth);
        ctx.fillStyle = 'rgba(16, 185, 129, 0.05)'; // Green tint for quiet days
        ctx.fillRect(x, startY, barWidth, chartHeight);
      }
    });
  }
};

// Chart.js default options for dark theme
const darkThemeOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: '#16161f',
      borderColor: '#252532',
      borderWidth: 1,
      titleColor: '#e8e8ed',
      bodyColor: '#7a7a8c'
    }
  },
  scales: {
    x: {
      grid: { display: false },
      ticks: { color: '#7a7a8c', font: { size: 9 } }
    },
    y: {
      grid: { color: '#1e1e2a' },
      ticks: { color: '#7a7a8c', font: { size: 9 } }
    }
  }
};

// Helper: Align all recent datasets to common time axis (uses LOD as reference)
const alignRecentData = (kpData, lodData, magData) => {
  if (!lodData || !lodData.labels || lodData.labels.length === 0) {
    return { kpData, lodData, magData };
  }

  const baseLabels = lodData.labels; // 90-day baseline
  const baseLength = baseLabels.length;

  // Align Kp to LOD time axis
  const kpAligned = { labels: baseLabels, data: Array(baseLength).fill(null), is_quiet: Array(baseLength).fill(null) };
  if (kpData && kpData.data) {
    const kpLen = kpData.labels.length;
    const kpStartIdx = baseLength - kpLen;

    if (kpStartIdx >= 0) {
      // Kp data fits within range - place at the end
      kpData.data.forEach((val, i) => {
        kpAligned.data[kpStartIdx + i] = val;
      });
      // Also align quiet-day flags if available
      if (kpData.is_quiet) {
        kpData.is_quiet.forEach((val, i) => {
          kpAligned.is_quiet[kpStartIdx + i] = val;
        });
      }
    } else {
      // Kp data is longer than range - take the most recent baseLength days
      const offset = kpLen - baseLength;
      for (let i = 0; i < baseLength; i++) {
        kpAligned.data[i] = kpData.data[offset + i];
      }
      if (kpData.is_quiet) {
        for (let i = 0; i < baseLength; i++) {
          kpAligned.is_quiet[i] = kpData.is_quiet[offset + i];
        }
      }
    }
  }

  // Align Mag to LOD time axis
  const magAligned = { labels: baseLabels, bou: Array(baseLength).fill(null), frd: Array(baseLength).fill(null), brw: Array(baseLength).fill(null), hon: Array(baseLength).fill(null), composite: Array(baseLength).fill(null) };
  if (magData && magData.labels) {
    const magLen = magData.labels.length;
    const magStartIdx = baseLength - magLen;

    if (magStartIdx >= 0) {
      // Mag data fits within range - place at the end
      const stations = ['bou', 'frd', 'brw', 'hon', 'composite'];
      stations.forEach(station => {
        if (magData[station]) {
          magData[station].forEach((val, i) => {
            magAligned[station][magStartIdx + i] = val;
          });
        }
      });
    } else {
      // Mag data is longer than range - take the most recent baseLength days
      const offset = magLen - baseLength;
      const stations = ['bou', 'frd', 'brw', 'hon', 'composite'];
      stations.forEach(station => {
        if (magData[station]) {
          for (let i = 0; i < baseLength; i++) {
            magAligned[station][i] = magData[station][offset + i];
          }
        }
      });
    }
  }

  return { kpData: kpAligned, lodData, magData: magAligned };
};

// Magnetometer station coordinates (fixed locations)
const MAG_STATION_COORDS = [
  { code: 'BOU', name: 'Boulder', lat: 40.1374, lng: -105.2371 },
  { code: 'FRD', name: 'Fredericksburg', lat: 38.2045, lng: -77.3705 },
  { code: 'BRW', name: 'Barrow', lat: 71.3212, lng: -156.6280 },
  { code: 'HON', name: 'Honolulu', lat: 21.3155, lng: -157.9241 },
];

// Globe component using globe.gl
const GlobeView = ({ seismicEvents, volcData }) => {
  const globeContainerRef = useRef(null);
  const globeInstanceRef = useRef(null);

  useEffect(() => {
    if (!globeContainerRef.current || typeof Globe === 'undefined') return;

    // Only create the globe once
    if (globeInstanceRef.current) return;

    const container = globeContainerRef.current;
    const width = container.clientWidth;
    const height = container.clientHeight || Math.max(400, width * 0.75);

    const globe = Globe()
      .globeImageUrl('//cdn.jsdelivr.net/npm/three-globe/example/img/earth-dark.jpg')
      .backgroundColor('rgba(0,0,0,0)')
      .showAtmosphere(true)
      .atmosphereColor('#3a228a')
      .atmosphereAltitude(0.15)
      .width(width)
      .height(height)
      .pointOfView({ lat: 10, lng: 170, altitude: 2.2 })
      (container);

    // Auto-rotate
    globe.controls().autoRotate = true;
    globe.controls().autoRotateSpeed = 0.3;
    globe.controls().enableZoom = true;

    globeInstanceRef.current = globe;

    // Fetch tectonic plate boundaries and render as paths
    fetch('https://raw.githubusercontent.com/fraxen/tectonicplates/master/GeoJSON/PB2002_boundaries.json')
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (!data || !data.features || !globeInstanceRef.current) return;
        const paths = [];
        data.features.forEach(f => {
          const lines = f.geometry.type === 'MultiLineString'
            ? f.geometry.coordinates
            : [f.geometry.coordinates];
          lines.forEach(line => {
            paths.push({ points: line });
          });
        });
        globeInstanceRef.current
          .pathsData(paths)
          .pathPoints('points')
          .pathPointLat(p => p[1])
          .pathPointLng(p => p[0])
          .pathColor(() => 'rgba(245, 158, 11, 0.25)')
          .pathStroke(0.4)
          .pathTransitionDuration(0);
      })
      .catch(() => {}); // fail silently

    // Use ResizeObserver to track container size changes (grid layout, window resize)
    const ro = new ResizeObserver(() => {
      if (globeInstanceRef.current && globeContainerRef.current) {
        const w = globeContainerRef.current.clientWidth;
        const h = globeContainerRef.current.clientHeight;
        if (w > 0 && h > 0) {
          globeInstanceRef.current.width(w).height(h);
        }
      }
    });
    ro.observe(container);

    return () => {
      ro.disconnect();
    };
  }, []);

  // Update data layers when data changes
  useEffect(() => {
    if (!globeInstanceRef.current) return;
    const globe = globeInstanceRef.current;

    // Build combined points data
    const pointsData = [];

    // 1. Earthquake epicenters (purple) - scaled by magnitude
    if (seismicEvents && seismicEvents.events) {
      seismicEvents.events.forEach(ev => {
        pointsData.push({
          lat: ev.lat,
          lng: ev.lon,
          size: Math.max(0.4, (ev.mag - 3.5) * 0.4),
          color: ev.mag >= 6.0 ? '#c084fc' : ev.mag >= 5.0 ? '#a78bfa' : '#8b5cf6',
          altitude: 0.005,
          type: 'earthquake',
          mag: ev.mag,
          depth_km: ev.depth_km,
          date: ev.date,
        });
      });
    }

    // 2. Active volcanoes (red)
    if (volcData && volcData.current_volcanoes) {
      volcData.current_volcanoes.forEach(v => {
        pointsData.push({
          lat: v.lat,
          lng: v.lon,
          size: 0.4,
          color: '#ef4444',
          altitude: 0.01,
          type: 'volcano',
          vName: v.name,
          vStatus: v.status,
        });
      });
    }

    // 3. Magnetometer stations (blue)
    MAG_STATION_COORDS.forEach(s => {
      pointsData.push({
        lat: s.lat,
        lng: s.lng,
        size: 0.35,
        color: '#4a9eff',
        altitude: 0.015,
        type: 'station',
        sCode: s.code,
        sName: s.name,
      });
    });

    const tooltipStyle = 'background:rgba(15,15,21,0.95);border:1px solid #252532;border-radius:6px;padding:8px 12px;font-family:Inter,system-ui,sans-serif;font-size:11px;color:#e8e8ed;line-height:1.5;max-width:220px;pointer-events:none;';
    const dimStyle = 'color:#7a7a8c;font-size:10px;';
    const valStyle = 'font-family:monospace;font-weight:600;';

    globe
      .pointsData(pointsData)
      .pointLat('lat')
      .pointLng('lng')
      .pointAltitude('altitude')
      .pointRadius('size')
      .pointColor('color')
      .pointLabel(d => {
        if (d.type === 'earthquake') {
          return `<div style="${tooltipStyle}border-left:3px solid #8b5cf6;">
            <div style="margin-bottom:4px;"><span style="${dimStyle}">DEEP EARTHQUAKE</span></div>
            <div><span style="${valStyle}color:#c084fc;">M${d.mag}</span> <span style="${dimStyle}">| ${d.depth_km.toFixed(0)}km depth</span></div>
            <div style="${dimStyle}">${d.date}</div>
            <div style="${dimStyle}">${d.lat.toFixed(2)}, ${d.lng.toFixed(2)}</div>
          </div>`;
        }
        if (d.type === 'volcano') {
          const statusColor = d.vStatus === 'erupting' ? '#ef4444' : d.vStatus === 'elevated' ? '#f59e0b' : '#7a7a8c';
          return `<div style="${tooltipStyle}border-left:3px solid #ef4444;">
            <div style="margin-bottom:4px;"><span style="${dimStyle}">VOLCANO</span></div>
            <div style="${valStyle}">${d.vName}</div>
            <div><span style="color:${statusColor};font-size:10px;font-weight:600;text-transform:uppercase;">${d.vStatus || 'active'}</span></div>
            <div style="${dimStyle}">${d.lat.toFixed(2)}, ${d.lng.toFixed(2)}</div>
          </div>`;
        }
        if (d.type === 'station') {
          return `<div style="${tooltipStyle}border-left:3px solid #4a9eff;">
            <div style="margin-bottom:4px;"><span style="${dimStyle}">MAG STATION</span></div>
            <div style="${valStyle}">${d.sCode}</div>
            <div style="${dimStyle}">${d.sName}</div>
            <div style="${dimStyle}">${d.lat.toFixed(2)}, ${d.lng.toFixed(2)}</div>
          </div>`;
        }
        return '';
      })
      .pointsMerge(false);

    // Add rings around earthquake epicenters for visibility
    const ringsData = [];
    if (seismicEvents && seismicEvents.events) {
      seismicEvents.events.forEach(ev => {
        ringsData.push({
          lat: ev.lat,
          lng: ev.lon,
          maxR: (ev.mag - 3.5) * 1.5,
          propagationSpeed: 1,
          repeatPeriod: ev.mag >= 5.5 ? 1200 : 2000,
          color: ev.mag >= 6.0 ? 'rgba(192,132,252,0.6)' : 'rgba(139,92,246,0.4)',
        });
      });
    }

    globe
      .ringsData(ringsData)
      .ringLat('lat')
      .ringLng('lng')
      .ringMaxRadius('maxR')
      .ringPropagationSpeed('propagationSpeed')
      .ringRepeatPeriod('repeatPeriod')
      .ringColor('color');

  }, [seismicEvents, volcData]);

  return (
    <div style={{ position: 'relative', height: '100%', minHeight: 400 }}>
      <div ref={globeContainerRef} style={{ width: '100%', height: '100%', cursor: 'grab' }} />
      {/* Legend overlay */}
      <div style={{
        position: 'absolute', bottom: 12, left: 12,
        background: 'rgba(15,15,21,0.85)', border: '1px solid #252532',
        borderRadius: 6, padding: '8px 12px', fontSize: 10, color: '#a8a8bc',
        display: 'flex', flexDirection: 'column', gap: 4,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ width: 8, height: 8, borderRadius: '50%', background: '#8b5cf6', display: 'inline-block' }} />
          Deep EQ (>300km)
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ width: 8, height: 8, borderRadius: '50%', background: '#ef4444', display: 'inline-block' }} />
          Active Volcanoes
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ width: 8, height: 8, borderRadius: '50%', background: '#4a9eff', display: 'inline-block' }} />
          Mag Stations
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ width: 12, height: 2, background: 'rgba(245, 158, 11, 0.5)', display: 'inline-block' }} />
          Plate Boundaries
        </div>
      </div>
    </div>
  );
};

// Polar motion spiral + Chandler residual charts
const PolarMotionCharts = ({ polarMotionData }) => {
  const spiralRef = useRef(null);
  const chandlerRef = useRef(null);
  const spiralChartRef = useRef(null);
  const chandlerChartRef = useRef(null);

  useEffect(() => {
    if (!polarMotionData || !polarMotionData.labels || polarMotionData.labels.length === 0) return;

    // --- Chart 1: X/Y Spiral Plot ---
    if (spiralChartRef.current) spiralChartRef.current.destroy();

    const n = polarMotionData.labels.length;
    // Color gradient: blue (old) to orange (recent)
    const spiralPoints = polarMotionData.pm_x.map((x, i) => ({
      x: x,
      y: polarMotionData.pm_y[i],
    }));

    // Create gradient colors for each point
    const colors = polarMotionData.labels.map((_, i) => {
      const t = i / (n - 1); // 0..1
      const r = Math.round(74 + t * (245 - 74));
      const g = Math.round(158 + t * (158 - 158));
      const b = Math.round(255 + t * (11 - 255));
      return `rgb(${r},${g},${b})`;
    });

    spiralChartRef.current = new Chart(spiralRef.current.getContext('2d'), {
      type: 'scatter',
      data: {
        datasets: [{
          data: spiralPoints,
          pointBackgroundColor: colors,
          pointBorderColor: colors,
          pointRadius: 1,
          pointHoverRadius: 3,
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: true,
        aspectRatio: 1,
        plugins: {
          legend: { display: false },
          tooltip: {
            backgroundColor: '#16161f',
            borderColor: '#252532',
            borderWidth: 1,
            titleColor: '#e8e8ed',
            bodyColor: '#7a7a8c',
            callbacks: {
              label: (ctx) => {
                const idx = ctx.dataIndex;
                return `${polarMotionData.labels[idx]} | X: ${ctx.parsed.x.toFixed(4)}″ Y: ${ctx.parsed.y.toFixed(4)}″`;
              }
            }
          }
        },
        scales: {
          x: {
            title: { display: true, text: 'PM X (arcsec)', color: '#7a7a8c', font: { size: 10 } },
            grid: { color: '#1e1e2a' },
            ticks: { color: '#7a7a8c', font: { size: 9 } },
          },
          y: {
            title: { display: true, text: 'PM Y (arcsec)', color: '#7a7a8c', font: { size: 10 } },
            grid: { color: '#1e1e2a' },
            ticks: { color: '#7a7a8c', font: { size: 9 } },
          }
        }
      }
    });

    // --- Chart 2: Chandler Residual Time Series ---
    if (chandlerChartRef.current) chandlerChartRef.current.destroy();

    // Downsample for performance (every 3rd point)
    const step = 3;
    const dsLabels = polarMotionData.labels.filter((_, i) => i % step === 0);
    const dsX = polarMotionData.pm_x_chandler.filter((_, i) => i % step === 0);
    const dsY = polarMotionData.pm_y_chandler.filter((_, i) => i % step === 0);

    chandlerChartRef.current = new Chart(chandlerRef.current.getContext('2d'), {
      type: 'line',
      data: {
        labels: dsLabels,
        datasets: [
          {
            label: 'Chandler X',
            data: dsX,
            borderColor: '#4a9eff',
            borderWidth: 1.5,
            tension: 0.3,
            pointRadius: 0,
          },
          {
            label: 'Chandler Y',
            data: dsY,
            borderColor: '#f59e0b',
            borderWidth: 1.5,
            tension: 0.3,
            pointRadius: 0,
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: true,
            position: 'top',
            labels: { color: '#7a7a8c', boxWidth: 12, padding: 8, font: { size: 10 } }
          },
          tooltip: {
            backgroundColor: '#16161f',
            borderColor: '#252532',
            borderWidth: 1,
            titleColor: '#e8e8ed',
            bodyColor: '#7a7a8c',
          }
        },
        scales: {
          x: {
            grid: { display: false },
            ticks: { color: '#7a7a8c', font: { size: 9 }, maxTicksLimit: 8 },
          },
          y: {
            title: { display: true, text: 'arcsec', color: '#7a7a8c', font: { size: 10 } },
            grid: { color: '#1e1e2a' },
            ticks: { color: '#7a7a8c', font: { size: 9 } },
          }
        }
      }
    });

    return () => {
      if (spiralChartRef.current) spiralChartRef.current.destroy();
      if (chandlerChartRef.current) chandlerChartRef.current.destroy();
    };
  }, [polarMotionData]);

  if (!polarMotionData || !polarMotionData.labels || polarMotionData.labels.length === 0) {
    return (
      <div style={{ padding: 20, textAlign: 'center', color: '#7a7a8c', fontSize: 13 }}>
        Polar motion data not yet available. Run the data pipeline to generate.
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div>
        <h4 style={{ fontSize: 12, color: '#7a7a8c', marginBottom: 8 }}>Polar Motion Spiral (10yr)</h4>
        <div style={{ maxWidth: 360, margin: '0 auto' }}>
          <canvas ref={spiralRef} />
        </div>
        <div style={{ fontSize: 10, color: '#7a7a8c', textAlign: 'center', marginTop: 4 }}>
          Color: <span style={{ color: '#4a9eff' }}>blue</span> = older → <span style={{ color: '#f59e0b' }}>orange</span> = recent
        </div>
      </div>
      <div>
        <h4 style={{ fontSize: 12, color: '#7a7a8c', marginBottom: 8 }}>Chandler Wobble Residual (~433d period)</h4>
        <div style={{ height: 160 }}>
          <canvas ref={chandlerRef} />
        </div>
      </div>
    </div>
  );
};

function ECDOWatchDashboard() {
  const [selectedTimeRange, setSelectedTimeRange] = useState('90d');
  const [historicalTimeRange, setHistoricalTimeRange] = useState(50);
  const [dataLoaded, setDataLoaded] = useState(false);
  const [kpData, setKpData] = useState(() => generateKpData());
  const [lodData, setLodData] = useState(() => generateLODData());
  const [c20Data, setC20Data] = useState({ labels: [], data: [] });
  const [magData, setMagData] = useState(() => generateMagData());
  const [aaData, setAaData] = useState(() => generateHistoricalAA(historicalTimeRange));
  const [pmData, setPmData] = useState(() => generateHistoricalPM(historicalTimeRange));
  const [coherenceData, setCoherenceData] = useState(null);
  const [seisData, setSeisData] = useState(null);
  const [volcData, setVolcData] = useState(null);
  const [polarMotionData, setPolarMotionData] = useState(null);
  const [seismicEvents, setSeismicEvents] = useState(null);
  const [compositeMetrics, setCompositeMetrics] = useState({ z: 0, flag: false, maxZ: 0 });
  const [statusLevel, setStatusLevel] = useState('NOMINAL');
  const [showStatusInfo, setShowStatusInfo] = useState(false);
  const [historicalExpanded, setHistoricalExpanded] = useState(false);
  const width = useWindowWidth();
  const [alignedData, setAlignedData] = useState(() => alignRecentData(kpData, lodData, magData));
  const [kpMetadata, setKpMetadata] = useState({});
  const [lodMetadata, setLodMetadata] = useState({});
  const [magMetadata, setMagMetadata] = useState({});

  // Load real data from JSON files when time range changes
  useEffect(() => {
    fetchDataFromJSON(selectedTimeRange).then(data => {
      if (data) {
        console.log(`Loaded data for ${selectedTimeRange}:`, { kpLabels: data.kpData.labels.length, lodLabels: data.lodData.labels.length, magLabels: data.magData.labels.length });
        setKpData(data.kpData);
        setLodData(data.lodData);
        setC20Data(data.c20Data);
        setAaData(data.aaData);
        setPmData(data.pmData);
        setMagData(data.magData);
        if (data.coherenceData) setCoherenceData(data.coherenceData);
        if (data.seisData) setSeisData(data.seisData);
        if (data.volcData) setVolcData(data.volcData);
        if (data.polarMotionData) setPolarMotionData(data.polarMotionData);
        if (data.seismicEventsData) setSeismicEvents(data.seismicEventsData);

        // Extract and store metadata
        setKpMetadata(data.kpData.metadata || {});
        setLodMetadata(data.lodData.metadata || {});
        setMagMetadata(data.magData.metadata || {});
      }
      setDataLoaded(true);
    }).catch(err => console.error('Error loading data:', err));
  }, [selectedTimeRange]);

  // Recalculate aligned data whenever individual datasets change
  useEffect(() => {
    const aligned = alignRecentData(kpData, lodData, magData);
    setAlignedData(aligned);
  }, [kpData, lodData, magData]);

  // Update historical data when time range changes
  useEffect(() => {
    setAaData(generateHistoricalAA(historicalTimeRange));
    setPmData(generateHistoricalPM(historicalTimeRange));
  }, [historicalTimeRange]);

  // Calculate composite z-score metrics dynamically
  useEffect(() => {
    if (alignedData.magData && alignedData.magData.composite && alignedData.magData.composite.length > 0) {
      const composite = alignedData.magData.composite;
      const validValues = composite.filter(v => v !== null);
      const recentValues = validValues.slice(-14); // Last 14 days with data
      if (recentValues.length > 0) {
        const maxAbsZ = Math.max(...recentValues.map(v => Math.abs(v)));
        const currentZ = composite[composite.length - 1];
        const flagged = maxAbsZ >= 2.5; // Flag if any recent value >= 2.5 sigma

        setCompositeMetrics({
          z: currentZ !== null ? currentZ.toFixed(2) : "—",
          flag: flagged,
          maxZ: maxAbsZ.toFixed(2)
        });
      }
    }
  }, [alignedData]);

  // Calculate watch status level from coherence data (or fall back to composite metrics)
  useEffect(() => {
    if (coherenceData && coherenceData.badge) {
      const badge = coherenceData.badge;
      if (badge === 'ORANGE') {
        setStatusLevel('WATCH');
      } else if (badge === 'YELLOW' || compositeMetrics.flag) {
        setStatusLevel('ELEVATED_DIAGNOSTIC');
      } else {
        setStatusLevel('NOMINAL');
      }
    } else if (compositeMetrics.flag) {
      setStatusLevel('ELEVATED_DIAGNOSTIC');
    } else {
      setStatusLevel('NOMINAL');
    }
  }, [compositeMetrics, coherenceData]);

  // Compute layout values
  const statusColorMap = { NOMINAL: '#10b981', ELEVATED_DIAGNOSTIC: '#f59e0b', WATCH: '#ef4444' };
  const statusColor = statusColorMap[statusLevel] || '#10b981';
  const gridCols4 = width >= 1000 ? 'repeat(4, 1fr)' : width >= 600 ? 'repeat(2, 1fr)' : '1fr';
  const gridCols3 = width >= 1000 ? 'repeat(3, 1fr)' : width >= 600 ? 'repeat(2, 1fr)' : '1fr';

  return (
    <div style={{ background: '#08080c', minHeight: '100vh', color: '#e8e8ed', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <style dangerouslySetInnerHTML={{__html: '@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } } .scene-tooltip { background: none !important; border: none !important; box-shadow: none !important; padding: 0 !important; }'}} />

      <div style={{ maxWidth: 1200, margin: '0 auto', padding: 20 }}>

        {/* Row 1: Merged Header Bar */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          background: '#0f0f15', border: '1px solid #252532',
          borderLeft: `4px solid ${statusColor}`,
          borderRadius: 8, padding: '8px 16px', marginBottom: 12,
          flexWrap: 'wrap', gap: 8, minHeight: 50,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <h1 style={{ fontSize: 16, fontWeight: 700, margin: 0, whiteSpace: 'nowrap' }}>ECDO Watch</h1>
            <div style={{
              width: 10, height: 10, borderRadius: '50%', background: statusColor,
              animation: 'pulse 2s infinite', flexShrink: 0,
            }} />
            <span style={{ fontFamily: 'monospace', fontSize: 12, color: statusColor, fontWeight: 600 }}>{statusLevel}</span>
            <button
              onClick={() => setShowStatusInfo(!showStatusInfo)}
              style={{
                background: 'transparent', border: '1px solid #7a7a8c', color: '#7a7a8c',
                borderRadius: '50%', width: 18, height: 18, fontSize: 11, fontWeight: 'bold',
                cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center',
                padding: 0, transition: 'all 0.2s ease', flexShrink: 0,
              }}
            >i</button>
          </div>
          <div style={{ display: 'flex', gap: 4 }}>
            {['30d', '90d', '1y', '5y', '10y'].map(range => (
              <button key={range} onClick={() => setSelectedTimeRange(range)} style={{
                background: selectedTimeRange === range ? '#4a9eff' : '#16161f',
                border: '1px solid #252532',
                color: selectedTimeRange === range ? '#fff' : '#7a7a8c',
                padding: '2px 8px', borderRadius: 3, fontSize: 9,
                fontFamily: 'monospace', cursor: 'pointer', transition: 'all 0.2s ease',
              }}>
                {range}
              </button>
            ))}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <DataFreshnessIndicator metadata={kpMetadata} />
            <a href="https://theethicalskeptic.com/2024/05/23/master-exothermic-core-mantle-decoupling-dzhanibekov-oscillation-theory/" target="_blank" rel="noopener noreferrer" style={{ color: '#4a9eff', textDecoration: 'none', fontSize: 10 }}>
              ECDO Theory
            </a>
          </div>
        </div>

        {/* Status info expandable panel */}
        {showStatusInfo && (
          <div style={{
            background: '#16161f', border: `1px solid ${statusColor}`, borderRadius: 8,
            padding: 16, marginBottom: 12, fontSize: 13, color: '#e8e8ed',
            borderLeft: `4px solid ${statusColor}`,
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }}>
              <div>
                <strong style={{ color: statusColor }}>What does this mean?</strong>
                <p style={{ margin: '8px 0 0 0', color: '#a8a8bc' }}>
                  {statusLevel === 'WATCH' ? 'Multiple independent geophysical channels are showing correlated anomalies. This indicates a potential system-wide geophysical perturbation and warrants close observation.' :
                   statusLevel === 'ELEVATED_DIAGNOSTIC' ? 'One monitoring channel has detected a statistical anomaly. This may represent normal variability or the beginning of a multi-channel event.' :
                   'All monitored geophysical signals are within their normal historical ranges. No anomalies detected.'}
                </p>
                <strong style={{ color: statusColor, display: 'block', marginTop: 12 }}>What we monitor:</strong>
                <ul style={{ margin: '8px 0 0 0', paddingLeft: 20, color: '#a8a8bc' }}>
                  <li>External Forcing (Kp index) - Solar wind energy coupling</li>
                  <li>Earth Orientation (LOD) - Rotational dynamics</li>
                  <li>Ground Magnetometer - Multi-station magnetic field anomalies</li>
                  <li>Cross-channel Coherence - Correlated signals across independent systems</li>
                  <li>Deep Seismicity - Mantle stress via deep earthquakes (&gt;300km)</li>
                  <li>Volcanic Activity - Global eruption monitoring and dispersion</li>
                </ul>
                <div style={{ marginTop: 8, fontSize: 11, color: '#7a7a8c' }}>
                  Experimental analysis tool, NOT a prediction system
                </div>
              </div>
              <button onClick={() => setShowStatusInfo(false)} style={{
                background: 'transparent', border: 'none', color: '#7a7a8c',
                fontSize: 18, cursor: 'pointer', padding: 0, minWidth: 20,
              }}>&#215;</button>
            </div>
          </div>
        )}

        {/* Row 2: Monitoring Panels - 4 column grid */}
        <div style={{ display: 'grid', gridTemplateColumns: gridCols4, gap: 12, marginBottom: 12 }}>

          {/* S1: Kp Gate */}
          <CompactCard step={1} title="Kp Gate" status="OPEN">
            <div style={{ height: 80 }}>
              <ChartComponent
                type="line"
                height={80}
                quietFlags={alignedData.kpData.is_quiet}
                data={{
                  labels: alignedData.kpData.labels,
                  datasets: [{
                    data: alignedData.kpData.data,
                    borderColor: '#4a9eff',
                    backgroundColor: 'rgba(74, 158, 255, 0.1)',
                    fill: true,
                    tension: 0.3,
                    pointRadius: 0,
                  }]
                }}
                options={{
                  ...darkThemeOptions,
                  scales: {
                    x: { ...darkThemeOptions.scales.x, display: false },
                    y: { ...darkThemeOptions.scales.y, ticks: { ...darkThemeOptions.scales.y.ticks, maxTicksLimit: 3 } },
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>
              <CompactMetric label="Kp Max" value="2.3" status="positive" />
              <CompactMetric label="Dst" value="-12 nT" status="positive" />
              <CompactMetric
                label="Quiet"
                value={kpData && kpData.is_quiet ? `${kpData.is_quiet.filter(x => x).length}/${kpData.is_quiet.length}` : "\u2014"}
                status="positive"
              />
            </div>
          </CompactCard>

          {/* S2: EOP / LOD */}
          <CompactCard step={2} title="EOP / LOD" status="NOMINAL">
            <div style={{ height: 100 }}>
              <ChartComponent
                type="line"
                height={100}
                data={{
                  labels: lodData.labels || [],
                  datasets: [
                    {
                      data: lodData.z_lod || [],
                      borderColor: '#4a9eff',
                      borderWidth: 1.5,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      data: lodData.z_pm_speed || [],
                      borderColor: '#f59e0b',
                      borderWidth: 1.5,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      data: lodData.eop_composite || [],
                      borderColor: '#ffffff',
                      borderWidth: 2,
                      tension: 0.3,
                      pointRadius: 0,
                    }
                  ]
                }}
                options={{
                  ...darkThemeOptions,
                  scales: {
                    x: { ...darkThemeOptions.scales.x, display: false },
                    y: { ...darkThemeOptions.scales.y, ticks: { ...darkThemeOptions.scales.y.ticks, maxTicksLimit: 3 } },
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>
              <CompactMetric
                label="LOD z"
                value={(() => { const arr = lodData.z_lod || []; const v = arr[arr.length - 1]; return v != null ? v.toFixed(2) : "\u2014"; })()}
                status={(() => { const arr = lodData.z_lod || []; const v = arr[arr.length - 1]; return v != null && Math.abs(v) >= 2.5 ? "warning" : "positive"; })()}
              />
              <CompactMetric
                label="PM z"
                value={(() => { const arr = lodData.z_pm_speed || []; const v = arr[arr.length - 1]; return v != null ? v.toFixed(2) : "\u2014"; })()}
                status={(() => { const arr = lodData.z_pm_speed || []; const v = arr[arr.length - 1]; return v != null && Math.abs(v) >= 2.5 ? "warning" : "positive"; })()}
              />
              <CompactMetric
                label="EOP"
                value={(() => { const arr = lodData.eop_composite || []; const v = arr[arr.length - 1]; return v != null ? v.toFixed(2) : "\u2014"; })()}
                status={(() => { const arr = lodData.eop_composite || []; const v = arr[arr.length - 1]; return v != null && Math.abs(v) >= 2.5 ? "warning" : "positive"; })()}
              />
            </div>
          </CompactCard>

          {/* S4: Magnetometer (visual order: after EOP) */}
          <CompactCard step={4} title="Magnetometer" status="NOMINAL">
            <div style={{ height: 100 }}>
              <ChartComponent
                type="line"
                height={100}
                data={{
                  labels: alignedData.magData.labels,
                  datasets: [
                    {
                      data: alignedData.magData.bou,
                      borderColor: 'rgba(74, 158, 255, 0.15)',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      data: alignedData.magData.frd,
                      borderColor: 'rgba(245, 158, 11, 0.15)',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      data: alignedData.magData.brw,
                      borderColor: 'rgba(16, 185, 129, 0.15)',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      data: alignedData.magData.hon,
                      borderColor: 'rgba(139, 92, 246, 0.15)',
                      borderWidth: 1,
                      tension: 0.3,
                      pointRadius: 0,
                    },
                    {
                      data: alignedData.magData.composite,
                      borderColor: '#ffffff',
                      borderWidth: 2,
                      tension: 0.3,
                      pointRadius: 0,
                    }
                  ]
                }}
                options={{
                  ...darkThemeOptions,
                  scales: {
                    x: { ...darkThemeOptions.scales.x, display: false },
                    y: { ...darkThemeOptions.scales.y, ticks: { ...darkThemeOptions.scales.y.ticks, maxTicksLimit: 3 } },
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>
              <CompactMetric label="Comp z" value={compositeMetrics.z} status={Math.abs(parseFloat(compositeMetrics.z)) >= 2.5 ? "negative" : "positive"} />
              <CompactMetric label="Max 14d" value={compositeMetrics.maxZ} status={compositeMetrics.flag ? "warning" : "positive"} />
              <CompactMetric label="Flag" value={compositeMetrics.flag ? "\u26a0" : "\u2713"} status={compositeMetrics.flag ? "warning" : "positive"} />
            </div>
          </CompactCard>

          {/* S3: C20 */}
          <CompactCard step={3} title="C20 Mass" status="OK" subtitle={c20Data && c20Data.labels ? `${c20Data.labels.length}d` : ''}>
            <div style={{ height: 80 }}>
              <ChartComponent
                type="line"
                height={80}
                data={{
                  labels: c20Data && c20Data.labels ? c20Data.labels : [],
                  datasets: [{
                    data: c20Data && c20Data.data ? c20Data.data : [],
                    borderColor: '#10b981',
                    tension: 0.3,
                    pointRadius: 0,
                  }]
                }}
                options={{
                  ...darkThemeOptions,
                  scales: {
                    x: { ...darkThemeOptions.scales.x, display: false },
                    y: { ...darkThemeOptions.scales.y, ticks: { ...darkThemeOptions.scales.y.ticks, maxTicksLimit: 3 } },
                  }
                }}
              />
            </div>
            <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>
              <CompactMetric label="C20 z" value={c20Data && c20Data.data && c20Data.data.length > 0 && c20Data.data[c20Data.data.length - 1] !== null ? c20Data.data[c20Data.data.length - 1].toFixed(2) : "\u2014"} status="positive" />
              <CompactMetric label="vs GIA" value="Normal" status="positive" />
            </div>
          </CompactCard>
        </div>

        {/* Row 3: Globe Centerpiece */}
        <div style={{ marginBottom: 12 }}>
          <div style={{ border: '1px solid #1e3a5f', borderRadius: 10, boxShadow: '0 0 20px rgba(74,158,255,0.05)' }}>
            <Card title="Geophysical Spatial Monitor" info={{
              description: "Interactive 3D globe showing the spatial distribution of deep earthquakes, active volcanoes, and magnetometer stations. The polar motion spiral reveals the Chandler wobble \u2014 a ~433-day oscillation with ~6m amplitude.",
              lookingFor: [
                "Geographic clustering of deep EQ along subduction zones (Ring of Fire)",
                "Global dispersion of volcanic activity (widely separated eruptions suggest mantle-wide stress)",
                "Polar motion spiral showing stable Chandler wobble amplitude (~0.1-0.2 arcsec)",
                "Changes in Chandler wobble amplitude or phase may indicate internal mass redistribution"
              ],
              dataSource: "USGS FDSN (earthquakes), Smithsonian GVP (volcanoes), IERS finals2000A (polar motion)"
            }}>
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
                gap: 16,
              }}>
                <div style={{ minHeight: 400 }}>
                  <GlobeView seismicEvents={seismicEvents} volcData={volcData} />
                </div>
                <div>
                  <PolarMotionCharts polarMotionData={polarMotionData} />
                </div>
              </div>
            </Card>
          </div>
        </div>

        {/* Row 4: Analysis Panels - 3 column grid */}
        <div style={{ display: 'grid', gridTemplateColumns: gridCols3, gap: 12, marginBottom: 12 }}>

          {/* S5: Coherence */}
          <CompactCard step={5} title="Coherence" status={coherenceData && coherenceData.badge === 'ORANGE' ? 'ELEVATED' : 'NOMINAL'}>
            {coherenceData && coherenceData.labels && coherenceData.labels.length > 0 ? (
              <>
                <div style={{ display: 'flex', gap: 4, marginBottom: 8 }}>
                  <CompactMetric
                    label="Quiet Days"
                    value={`${coherenceData.quiet_day_count}/${coherenceData.total_days}`}
                    status="positive"
                  />
                  <CompactMetric
                    label="Score"
                    value={coherenceData.latest_watch_score != null ? coherenceData.latest_watch_score.toFixed(0) : "\u2014"}
                    status={coherenceData.badge === 'GREEN' ? 'positive' : coherenceData.badge === 'YELLOW' ? 'warning' : coherenceData.badge === 'ORANGE' ? 'negative' : undefined}
                  />
                  <CompactMetric
                    label="Badge"
                    value={coherenceData.badge}
                    status={coherenceData.badge === 'GREEN' ? 'positive' : coherenceData.badge === 'YELLOW' ? 'warning' : coherenceData.badge === 'ORANGE' ? 'negative' : undefined}
                  />
                </div>
                <div style={{ height: 100, marginBottom: 8 }}>
                  <ChartComponent
                    type="line"
                    height={100}
                    data={{
                      labels: coherenceData.labels,
                      datasets: [
                        {
                          label: 'EOP',
                          data: coherenceData.eop_composite,
                          borderColor: '#4a9eff',
                          borderWidth: 1.5,
                          tension: 0.3,
                          pointRadius: 0,
                        },
                        {
                          label: 'MAG',
                          data: coherenceData.mag_composite,
                          borderColor: '#f59e0b',
                          borderWidth: 1.5,
                          tension: 0.3,
                          pointRadius: 0,
                        }
                      ]
                    }}
                    options={{
                      ...darkThemeOptions,
                      plugins: {
                        ...darkThemeOptions.plugins,
                        legend: {
                          display: true,
                          position: 'top',
                          labels: { color: '#7a7a8c', boxWidth: 8, padding: 6, font: { size: 9 } }
                        }
                      },
                      scales: {
                        x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 5 } },
                        y: { ...darkThemeOptions.scales.y },
                      }
                    }}
                  />
                </div>
                <div style={{ height: 60, marginBottom: 8 }}>
                  <ChartComponent
                    type="line"
                    height={60}
                    data={{
                      labels: coherenceData.labels,
                      quietFlags: coherenceData.quiet,
                      datasets: [{
                        data: coherenceData.watch_score,
                        borderColor: '#10b981',
                        backgroundColor: 'rgba(16, 185, 129, 0.1)',
                        fill: true,
                        tension: 0.3,
                        pointRadius: 0,
                      }]
                    }}
                    options={{
                      ...darkThemeOptions,
                      plugins: { ...darkThemeOptions.plugins, legend: { display: false } },
                      scales: {
                        x: { ...darkThemeOptions.scales.x, display: false },
                        y: { ...darkThemeOptions.scales.y, min: 0, max: 100 },
                      }
                    }}
                    quietFlags={coherenceData.quiet}
                  />
                </div>
                <div style={{ display: 'flex', gap: 4 }}>
                  <CompactMetric
                    label="EOP&#8596;MAG r"
                    value={coherenceData.correlation != null ? coherenceData.correlation.toFixed(2) : "n/a"}
                    status={coherenceData.correlation != null && Math.abs(coherenceData.correlation) >= 0.5 ? "warning" : "positive"}
                  />
                  <CompactMetric
                    label="N quiet"
                    value={`${coherenceData.quiet_day_count}`}
                    status={coherenceData.quiet_day_count >= 10 ? "positive" : "warning"}
                  />
                </div>
              </>
            ) : (
              <div style={{ padding: 16, textAlign: 'center', color: '#7a7a8c', fontSize: 11 }}>
                Coherence data not yet available.
              </div>
            )}
          </CompactCard>

          {/* S6: Deep Seismicity */}
          <CompactCard step={6} title="Deep Seismicity" status={(() => {
            if (!seisData || !seisData.z_eq_count) return 'NOMINAL';
            const recent = seisData.z_eq_count.slice(-14).filter(v => v != null);
            const maxZ = recent.length > 0 ? Math.max(...recent.map(v => Math.abs(v))) : 0;
            return maxZ >= 2.5 ? 'ELEVATED' : 'NOMINAL';
          })()}>
            {seisData && seisData.labels && seisData.labels.length > 0 ? (
              <>
                <div style={{ height: 120 }}>
                  <ChartComponent
                    type="line"
                    height={120}
                    data={{
                      labels: seisData.labels,
                      datasets: [
                        {
                          label: 'Daily deep EQ',
                          data: seisData.eq_count,
                          borderColor: '#8b5cf6',
                          backgroundColor: 'rgba(139, 92, 246, 0.1)',
                          fill: true,
                          borderWidth: 1.5,
                          tension: 0.3,
                          pointRadius: 0,
                        },
                        {
                          label: '30d avg',
                          data: seisData.rolling_30d_count,
                          borderColor: '#ffffff',
                          borderWidth: 2,
                          borderDash: [5, 3],
                          tension: 0.3,
                          pointRadius: 0,
                        }
                      ]
                    }}
                    options={{
                      ...darkThemeOptions,
                      plugins: {
                        ...darkThemeOptions.plugins,
                        legend: {
                          display: true,
                          position: 'top',
                          labels: { color: '#7a7a8c', boxWidth: 8, padding: 6, font: { size: 9 } }
                        }
                      },
                      scales: {
                        x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 5 } },
                        y: { ...darkThemeOptions.scales.y },
                      }
                    }}
                  />
                </div>
                <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>
                  <CompactMetric
                    label="30d avg"
                    value={(() => {
                      const arr = seisData.rolling_30d_count || [];
                      const v = arr[arr.length - 1];
                      return v != null ? v.toFixed(1) : "\u2014";
                    })()}
                    status="positive"
                  />
                  <CompactMetric
                    label="Max z 14d"
                    value={(() => {
                      const arr = (seisData.z_eq_count || []).slice(-14).filter(v => v != null);
                      return arr.length > 0 ? Math.max(...arr.map(v => Math.abs(v))).toFixed(2) : "\u2014";
                    })()}
                    status={(() => {
                      const arr = (seisData.z_eq_count || []).slice(-14).filter(v => v != null);
                      const maxZ = arr.length > 0 ? Math.max(...arr.map(v => Math.abs(v))) : 0;
                      return maxZ >= 2.5 ? "warning" : "positive";
                    })()}
                  />
                  <CompactMetric
                    label="Energy"
                    value={(() => {
                      const arr = (seisData.energy_log10 || []).slice(-30).filter(v => v != null);
                      if (arr.length === 0) return "\u2014";
                      return (arr.reduce((a, b) => a + b, 0) / arr.length).toFixed(1);
                    })()}
                    status="positive"
                  />
                </div>
              </>
            ) : (
              <div style={{ padding: 16, textAlign: 'center', color: '#7a7a8c', fontSize: 11 }}>
                Deep seismicity data not yet available.
              </div>
            )}
          </CompactCard>

          {/* S7: Volcanic */}
          <CompactCard step={7} title="Volcanic" status={(() => {
            if (!volcData || !volcData.z_active_count) return 'NOMINAL';
            const recent = volcData.z_active_count.filter(v => v != null);
            const latest = recent.length > 0 ? recent[recent.length - 1] : 0;
            return Math.abs(latest) >= 2.0 ? 'ELEVATED' : 'NOMINAL';
          })()}>
            {volcData && volcData.labels && volcData.labels.length > 0 ? (
              <>
                <div style={{ height: 100 }}>
                  <ChartComponent
                    type="bar"
                    height={100}
                    data={{
                      labels: volcData.labels,
                      datasets: [{
                        data: volcData.active_count,
                        backgroundColor: volcData.z_active_count
                          ? volcData.z_active_count.map(z => z != null && Math.abs(z) >= 2.0 ? '#ef4444' : '#f59e0b')
                          : '#f59e0b',
                        borderRadius: 2,
                      }]
                    }}
                    options={{
                      ...darkThemeOptions,
                      plugins: { ...darkThemeOptions.plugins, legend: { display: false } },
                      scales: {
                        x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 5 } },
                        y: { ...darkThemeOptions.scales.y, beginAtZero: true },
                      }
                    }}
                  />
                </div>
                <div style={{ display: 'flex', gap: 4, marginTop: 8 }}>
                  <CompactMetric
                    label="Active"
                    value={(() => {
                      const arr = volcData.active_count || [];
                      return arr.length > 0 ? arr[arr.length - 1] : "\u2014";
                    })()}
                    status="positive"
                  />
                  <CompactMetric
                    label="New 30d"
                    value={(() => {
                      const arr = volcData.new_eruptions || [];
                      return arr.length > 0 ? arr[arr.length - 1] : "\u2014";
                    })()}
                    status={(() => {
                      const arr = volcData.new_eruptions || [];
                      const v = arr.length > 0 ? arr[arr.length - 1] : 0;
                      return v >= 3 ? "warning" : "positive";
                    })()}
                  />
                  <CompactMetric
                    label="Disp km"
                    value={(() => {
                      const arr = volcData.dispersion_km || [];
                      const v = arr.length > 0 ? arr[arr.length - 1] : null;
                      return v != null ? Math.round(v).toLocaleString() : "\u2014";
                    })()}
                    status="positive"
                  />
                </div>
                {volcData.current_volcanoes && volcData.current_volcanoes.length > 0 && (
                  <div style={{ marginTop: 8, padding: 8, background: '#16161f', borderRadius: 4, fontSize: 10, color: '#a8a8bc', maxHeight: 60, overflowY: 'auto' }}>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                      {volcData.current_volcanoes.slice(0, 15).map((v, idx) => (
                        <span key={idx} style={{
                          padding: '1px 6px', borderRadius: 3, fontSize: 9,
                          background: v.status === 'erupting' ? 'rgba(239,68,68,0.2)' : 'rgba(107,114,128,0.2)',
                          color: v.status === 'erupting' ? '#ef4444' : '#7a7a8c',
                        }}>
                          {v.name}
                        </span>
                      ))}
                      {volcData.current_volcanoes.length > 15 && (
                        <span style={{ color: '#7a7a8c', fontSize: 9 }}>+{volcData.current_volcanoes.length - 15}</span>
                      )}
                    </div>
                  </div>
                )}
              </>
            ) : (
              <div style={{ padding: 16, textAlign: 'center', color: '#7a7a8c', fontSize: 11 }}>
                Volcanic data not yet available.
              </div>
            )}
          </CompactCard>
        </div>

        {/* Row 5: Historical Context (collapsible) */}
        <div style={{ background: '#0f0f15', border: '1px solid #252532', borderRadius: 8, overflow: 'hidden', marginBottom: 12 }}>
          <div
            onClick={() => setHistoricalExpanded(!historicalExpanded)}
            style={{
              display: 'flex', alignItems: 'center', gap: 8,
              padding: '12px 16px', cursor: 'pointer',
              background: '#16161f', userSelect: 'none',
            }}
          >
            <span style={{ fontSize: 10, color: '#7a7a8c', transition: 'transform 0.2s', display: 'inline-block', transform: historicalExpanded ? 'rotate(90deg)' : 'rotate(0deg)' }}>&#9654;</span>
            <h3 style={{ fontSize: 14, fontWeight: 600, margin: 0, color: '#e8e8ed' }}>Century-Scale Historical Context</h3>
          </div>
          {historicalExpanded && (
            <div style={{ padding: 16 }}>
              <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' }}>
                {[10, 50, 100, 150].map(y => (
                  <button key={y} onClick={() => setHistoricalTimeRange(y)} style={{
                    background: historicalTimeRange === y ? '#4a9eff' : '#16161f',
                    border: '1px solid #252532', color: historicalTimeRange === y ? '#fff' : '#7a7a8c',
                    padding: '4px 12px', borderRadius: 4, fontSize: 11, fontFamily: 'monospace', cursor: 'pointer',
                  }}>{y}Y</button>
                ))}
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 16 }}>
                <div>
                  <h4 style={{ fontSize: 12, color: '#7a7a8c', marginBottom: 8 }}>Geomagnetic Ap Index (since 1932)</h4>
                  <div style={{ height: 160 }}>
                    <ChartComponent
                      type="line"
                      height={160}
                      data={{
                        labels: aaData.labels,
                        datasets: [{
                          data: aaData.data,
                          borderColor: '#f59e0b',
                          backgroundColor: 'rgba(245, 158, 11, 0.1)',
                          fill: true, tension: 0.3, pointRadius: 0,
                        }]
                      }}
                      options={{
                        ...darkThemeOptions,
                        scales: {
                          ...darkThemeOptions.scales,
                          x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 10 } },
                          y: { ...darkThemeOptions.scales.y },
                        }
                      }}
                    />
                  </div>
                </div>
                <div>
                  <h4 style={{ fontSize: 12, color: '#7a7a8c', marginBottom: 8 }}>Polar Motion Amplitude (since 1846)</h4>
                  <div style={{ height: 160 }}>
                    <ChartComponent
                      type="line"
                      height={160}
                      data={{
                        labels: pmData.labels,
                        datasets: [{
                          data: pmData.data,
                          borderColor: '#10b981',
                          backgroundColor: 'rgba(16, 185, 129, 0.1)',
                          fill: true, tension: 0.3, pointRadius: 0,
                        }]
                      }}
                      options={{
                        ...darkThemeOptions,
                        scales: {
                          ...darkThemeOptions.scales,
                          x: { ...darkThemeOptions.scales.x, display: true, ticks: { maxTicksLimit: 10 } },
                          y: { ...darkThemeOptions.scales.y },
                        }
                      }}
                    />
                  </div>
                </div>
              </div>
              <div style={{ display: 'flex', gap: 16, marginTop: 16, flexWrap: 'wrap' }}>
                <Metric label="Ap Record" value="1932&#8211;Now" />
                <Metric label="PM Record" value="1846&#8211;Now" />
                <Metric label="LOD Record" value="1623&#8211;Now" />
                <Metric label="Current Regime" value="Within Bounds" status="positive" />
              </div>
              <div style={{ marginTop: 16, padding: 12, background: '#16161f', borderRadius: 6, fontSize: 11, color: '#7a7a8c' }}>
                <strong>Data sources:</strong> Ap index from GFZ (1932&#8211;present); Polar motion from IERS C01 (1846&#8211;present); LOD from IERS (yearly since 1623).
              </div>
            </div>
          )}
        </div>

        <DataSourceFooter kpMetadata={kpMetadata} lodMetadata={lodMetadata} magMetadata={magMetadata} />

        <footer style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid #252532', fontSize: 11, color: '#7a7a8c', textAlign: 'left' }}>
          Experimental analysis tool, NOT a prediction system. Watch levels indicate statistical anomalies relative to historical baselines.
        </footer>
      </div>
    </div>
  );
}
